-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity IFFT_AP_buffer_write is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_st_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    out_st_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    out_st_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    out_st_empty_n : IN STD_LOGIC;
    out_st_read : OUT STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    out1_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    out1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    out1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    out1_empty_n : IN STD_LOGIC;
    out1_read : OUT STD_LOGIC;
    out2_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    out2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    out2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    out2_empty_n : IN STD_LOGIC;
    out2_read : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of IFFT_AP_buffer_write is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal out1_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal out2_blk_n : STD_LOGIC;
    signal out2_read_reg_169 : STD_LOGIC_VECTOR (63 downto 0);
    signal out1_read_reg_174 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_132_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_i_i_reg_179 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_out_st_read : STD_LOGIC;
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWVALID : STD_LOGIC;
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WVALID : STD_LOGIC;
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WSTRB : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WLAST : STD_LOGIC;
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARVALID : STD_LOGIC;
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_RREADY : STD_LOGIC;
    signal grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_BREADY : STD_LOGIC;
    signal grp_dataflow_parent_loop_proc18_fu_100_ap_start : STD_LOGIC;
    signal grp_dataflow_parent_loop_proc18_fu_100_ap_done : STD_LOGIC;
    signal grp_dataflow_parent_loop_proc18_fu_100_ap_ready : STD_LOGIC;
    signal grp_dataflow_parent_loop_proc18_fu_100_ap_idle : STD_LOGIC;
    signal grp_dataflow_parent_loop_proc18_fu_100_ap_continue : STD_LOGIC;
    signal grp_dataflow_parent_loop_proc18_fu_100_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state4_ignore_call14 : BOOLEAN;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_sync_grp_dataflow_parent_loop_proc18_fu_100_ap_ready : STD_LOGIC;
    signal ap_sync_grp_dataflow_parent_loop_proc18_fu_100_ap_done : STD_LOGIC;
    signal ap_block_state5_on_subcall_done : BOOLEAN;
    signal ap_sync_reg_grp_dataflow_parent_loop_proc18_fu_100_ap_ready : STD_LOGIC := '0';
    signal ap_sync_reg_grp_dataflow_parent_loop_proc18_fu_100_ap_done : STD_LOGIC := '0';
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_state4 : BOOLEAN;
    signal grp_fu_132_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_132_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_132_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal grp_fu_132_p00 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_132_p10 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component IFFT_AP_dataflow_parent_loop_proc18 IS
    port (
        mul_i : IN STD_LOGIC_VECTOR (23 downto 0);
        out_st_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        out_st_empty_n : IN STD_LOGIC;
        out_st_read : OUT STD_LOGIC;
        ctrl1_reg_ls : IN STD_LOGIC_VECTOR (7 downto 0);
        ctrl2_reg_pn : IN STD_LOGIC_VECTOR (7 downto 0);
        actp_reg_pool_size : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_AWREADY : IN STD_LOGIC;
        m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WVALID : OUT STD_LOGIC;
        m_axi_gmem_WREADY : IN STD_LOGIC;
        m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
        m_axi_gmem_WLAST : OUT STD_LOGIC;
        m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_ARREADY : IN STD_LOGIC;
        m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RVALID : IN STD_LOGIC;
        m_axi_gmem_RREADY : OUT STD_LOGIC;
        m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        m_axi_gmem_RLAST : IN STD_LOGIC;
        m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BVALID : IN STD_LOGIC;
        m_axi_gmem_BREADY : OUT STD_LOGIC;
        m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        out1 : IN STD_LOGIC_VECTOR (63 downto 0);
        out2 : IN STD_LOGIC_VECTOR (63 downto 0);
        layer2_reg_ifs : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ctrl1_reg_ls_ap_vld : IN STD_LOGIC;
        ctrl2_reg_pn_ap_vld : IN STD_LOGIC;
        actp_reg_pool_size_ap_vld : IN STD_LOGIC;
        out1_ap_vld : IN STD_LOGIC;
        out2_ap_vld : IN STD_LOGIC;
        layer2_reg_ifs_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component IFFT_AP_mul_mul_16ns_8ns_24_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;



begin
    grp_dataflow_parent_loop_proc18_fu_100 : component IFFT_AP_dataflow_parent_loop_proc18
    port map (
        mul_i => mul_i_i_reg_179,
        out_st_dout => out_st_dout,
        out_st_empty_n => out_st_empty_n,
        out_st_read => grp_dataflow_parent_loop_proc18_fu_100_out_st_read,
        ctrl1_reg_ls => p_read,
        ctrl2_reg_pn => p_read1,
        actp_reg_pool_size => p_read4,
        m_axi_gmem_AWVALID => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY => m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWADDR,
        m_axi_gmem_AWID => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWID,
        m_axi_gmem_AWLEN => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WVALID,
        m_axi_gmem_WREADY => m_axi_gmem_WREADY,
        m_axi_gmem_WDATA => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WLAST,
        m_axi_gmem_WID => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WID,
        m_axi_gmem_WUSER => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY => ap_const_logic_0,
        m_axi_gmem_ARADDR => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARADDR,
        m_axi_gmem_ARID => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARID,
        m_axi_gmem_ARLEN => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID => ap_const_logic_0,
        m_axi_gmem_RREADY => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_RREADY,
        m_axi_gmem_RDATA => ap_const_lv128_lc_1,
        m_axi_gmem_RLAST => ap_const_logic_0,
        m_axi_gmem_RID => ap_const_lv1_0,
        m_axi_gmem_RFIFONUM => ap_const_lv9_0,
        m_axi_gmem_RUSER => ap_const_lv1_0,
        m_axi_gmem_RRESP => ap_const_lv2_0,
        m_axi_gmem_BVALID => m_axi_gmem_BVALID,
        m_axi_gmem_BREADY => grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_BREADY,
        m_axi_gmem_BRESP => m_axi_gmem_BRESP,
        m_axi_gmem_BID => m_axi_gmem_BID,
        m_axi_gmem_BUSER => m_axi_gmem_BUSER,
        out1 => out1_read_reg_174,
        out2 => out2_read_reg_169,
        layer2_reg_ifs => p_read3,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ctrl1_reg_ls_ap_vld => ap_const_logic_1,
        ctrl2_reg_pn_ap_vld => ap_const_logic_1,
        actp_reg_pool_size_ap_vld => ap_const_logic_1,
        out1_ap_vld => ap_const_logic_1,
        out2_ap_vld => ap_const_logic_1,
        layer2_reg_ifs_ap_vld => ap_const_logic_1,
        ap_start => grp_dataflow_parent_loop_proc18_fu_100_ap_start,
        ap_done => grp_dataflow_parent_loop_proc18_fu_100_ap_done,
        ap_ready => grp_dataflow_parent_loop_proc18_fu_100_ap_ready,
        ap_idle => grp_dataflow_parent_loop_proc18_fu_100_ap_idle,
        ap_continue => grp_dataflow_parent_loop_proc18_fu_100_ap_continue);

    mul_mul_16ns_8ns_24_4_1_U435 : component IFFT_AP_mul_mul_16ns_8ns_24_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_132_p0,
        din1 => grp_fu_132_p1,
        ce => grp_fu_132_ce,
        dout => grp_fu_132_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_dataflow_parent_loop_proc18_fu_100_ap_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_dataflow_parent_loop_proc18_fu_100_ap_done <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_sync_reg_grp_dataflow_parent_loop_proc18_fu_100_ap_done <= ap_const_logic_0;
                elsif ((grp_dataflow_parent_loop_proc18_fu_100_ap_done = ap_const_logic_1)) then 
                    ap_sync_reg_grp_dataflow_parent_loop_proc18_fu_100_ap_done <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_dataflow_parent_loop_proc18_fu_100_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_dataflow_parent_loop_proc18_fu_100_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_sync_reg_grp_dataflow_parent_loop_proc18_fu_100_ap_ready <= ap_const_logic_0;
                elsif ((grp_dataflow_parent_loop_proc18_fu_100_ap_ready = ap_const_logic_1)) then 
                    ap_sync_reg_grp_dataflow_parent_loop_proc18_fu_100_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_dataflow_parent_loop_proc18_fu_100_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dataflow_parent_loop_proc18_fu_100_ap_start_reg <= ap_const_logic_0;
            else
                if ((((ap_sync_grp_dataflow_parent_loop_proc18_fu_100_ap_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((out1_empty_n = ap_const_logic_0) or (out2_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
                    grp_dataflow_parent_loop_proc18_fu_100_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dataflow_parent_loop_proc18_fu_100_ap_ready = ap_const_logic_1)) then 
                    grp_dataflow_parent_loop_proc18_fu_100_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                mul_i_i_reg_179 <= grp_fu_132_p2;
                out1_read_reg_174 <= out1_dout;
                out2_read_reg_169 <= out2_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, out1_empty_n, out2_empty_n, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_block_state5_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if ((not(((out1_empty_n = ap_const_logic_0) or (out2_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(out1_empty_n, out2_empty_n)
    begin
        if (((out1_empty_n = ap_const_logic_0) or (out2_empty_n = ap_const_logic_0))) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state5_on_subcall_done)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state4_assign_proc : process(out1_empty_n, out2_empty_n)
    begin
                ap_block_state4 <= ((out1_empty_n = ap_const_logic_0) or (out2_empty_n = ap_const_logic_0));
    end process;


    ap_block_state4_ignore_call14_assign_proc : process(out1_empty_n, out2_empty_n)
    begin
                ap_block_state4_ignore_call14 <= ((out1_empty_n = ap_const_logic_0) or (out2_empty_n = ap_const_logic_0));
    end process;


    ap_block_state5_on_subcall_done_assign_proc : process(ap_sync_grp_dataflow_parent_loop_proc18_fu_100_ap_ready, ap_sync_grp_dataflow_parent_loop_proc18_fu_100_ap_done)
    begin
                ap_block_state5_on_subcall_done <= ((ap_sync_grp_dataflow_parent_loop_proc18_fu_100_ap_ready and ap_sync_grp_dataflow_parent_loop_proc18_fu_100_ap_done) = ap_const_logic_0);
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state5, ap_block_state5_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_sync_grp_dataflow_parent_loop_proc18_fu_100_ap_done <= (grp_dataflow_parent_loop_proc18_fu_100_ap_done or ap_sync_reg_grp_dataflow_parent_loop_proc18_fu_100_ap_done);
    ap_sync_grp_dataflow_parent_loop_proc18_fu_100_ap_ready <= (grp_dataflow_parent_loop_proc18_fu_100_ap_ready or ap_sync_reg_grp_dataflow_parent_loop_proc18_fu_100_ap_ready);

    grp_dataflow_parent_loop_proc18_fu_100_ap_continue_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            grp_dataflow_parent_loop_proc18_fu_100_ap_continue <= ap_const_logic_1;
        else 
            grp_dataflow_parent_loop_proc18_fu_100_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    grp_dataflow_parent_loop_proc18_fu_100_ap_start <= grp_dataflow_parent_loop_proc18_fu_100_ap_start_reg;

    grp_fu_132_ce_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, out1_empty_n, out2_empty_n, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_logic_1 = ap_CS_fsm_state1) and ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) or ((ap_const_logic_1 = ap_CS_fsm_state4) and ((out1_empty_n = ap_const_logic_0) or (out2_empty_n = ap_const_logic_0))))) then 
            grp_fu_132_ce <= ap_const_logic_0;
        else 
            grp_fu_132_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_132_p0 <= grp_fu_132_p00(16 - 1 downto 0);
    grp_fu_132_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read2),24));
    grp_fu_132_p1 <= grp_fu_132_p10(8 - 1 downto 0);
    grp_fu_132_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read1),24));
    m_axi_gmem_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_ARID <= ap_const_lv1_0;
    m_axi_gmem_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_ARVALID <= ap_const_logic_0;
    m_axi_gmem_AWADDR <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWADDR;
    m_axi_gmem_AWBURST <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWBURST;
    m_axi_gmem_AWCACHE <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWCACHE;
    m_axi_gmem_AWID <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWID;
    m_axi_gmem_AWLEN <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWLEN;
    m_axi_gmem_AWLOCK <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWLOCK;
    m_axi_gmem_AWPROT <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWPROT;
    m_axi_gmem_AWQOS <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWQOS;
    m_axi_gmem_AWREGION <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWREGION;
    m_axi_gmem_AWSIZE <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWSIZE;
    m_axi_gmem_AWUSER <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWUSER;

    m_axi_gmem_AWVALID_assign_proc : process(ap_CS_fsm_state4, grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWVALID, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem_AWVALID <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_AWVALID;
        else 
            m_axi_gmem_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem_BREADY_assign_proc : process(ap_CS_fsm_state4, grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_BREADY, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem_BREADY <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_BREADY;
        else 
            m_axi_gmem_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_RREADY <= ap_const_logic_0;
    m_axi_gmem_WDATA <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WDATA;
    m_axi_gmem_WID <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WID;
    m_axi_gmem_WLAST <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WLAST;
    m_axi_gmem_WSTRB <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WSTRB;
    m_axi_gmem_WUSER <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WUSER;

    m_axi_gmem_WVALID_assign_proc : process(ap_CS_fsm_state4, grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WVALID, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem_WVALID <= grp_dataflow_parent_loop_proc18_fu_100_m_axi_gmem_WVALID;
        else 
            m_axi_gmem_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    out1_blk_n_assign_proc : process(out1_empty_n, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out1_blk_n <= out1_empty_n;
        else 
            out1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out1_read_assign_proc : process(out1_empty_n, out2_empty_n, ap_CS_fsm_state4)
    begin
        if ((not(((out1_empty_n = ap_const_logic_0) or (out2_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out1_read <= ap_const_logic_1;
        else 
            out1_read <= ap_const_logic_0;
        end if; 
    end process;


    out2_blk_n_assign_proc : process(out2_empty_n, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out2_blk_n <= out2_empty_n;
        else 
            out2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out2_read_assign_proc : process(out1_empty_n, out2_empty_n, ap_CS_fsm_state4)
    begin
        if ((not(((out1_empty_n = ap_const_logic_0) or (out2_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out2_read <= ap_const_logic_1;
        else 
            out2_read <= ap_const_logic_0;
        end if; 
    end process;


    out_st_read_assign_proc : process(grp_dataflow_parent_loop_proc18_fu_100_out_st_read, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            out_st_read <= grp_dataflow_parent_loop_proc18_fu_100_out_st_read;
        else 
            out_st_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
