// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fwd_fft_Mem_Patch_Gen (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        in1,
        in2,
        c_ifmap_patch_st_din,
        c_ifmap_patch_st_full_n,
        c_ifmap_patch_st_write,
        ctrl1_reg,
        ctrl2_reg,
        layer1_reg,
        layer2_reg,
        ctrl1_reg_c21_din,
        ctrl1_reg_c21_full_n,
        ctrl1_reg_c21_write,
        ctrl2_reg_c26_din,
        ctrl2_reg_c26_full_n,
        ctrl2_reg_c26_write,
        layer1_reg_c31_din,
        layer1_reg_c31_full_n,
        layer1_reg_c31_write
);

parameter    ap_ST_fsm_state1 = 28'd1;
parameter    ap_ST_fsm_state2 = 28'd2;
parameter    ap_ST_fsm_state3 = 28'd4;
parameter    ap_ST_fsm_state4 = 28'd8;
parameter    ap_ST_fsm_state5 = 28'd16;
parameter    ap_ST_fsm_state6 = 28'd32;
parameter    ap_ST_fsm_state7 = 28'd64;
parameter    ap_ST_fsm_state8 = 28'd128;
parameter    ap_ST_fsm_state9 = 28'd256;
parameter    ap_ST_fsm_state10 = 28'd512;
parameter    ap_ST_fsm_state11 = 28'd1024;
parameter    ap_ST_fsm_state12 = 28'd2048;
parameter    ap_ST_fsm_state13 = 28'd4096;
parameter    ap_ST_fsm_state14 = 28'd8192;
parameter    ap_ST_fsm_state15 = 28'd16384;
parameter    ap_ST_fsm_state16 = 28'd32768;
parameter    ap_ST_fsm_state17 = 28'd65536;
parameter    ap_ST_fsm_state18 = 28'd131072;
parameter    ap_ST_fsm_state19 = 28'd262144;
parameter    ap_ST_fsm_state20 = 28'd524288;
parameter    ap_ST_fsm_state21 = 28'd1048576;
parameter    ap_ST_fsm_state22 = 28'd2097152;
parameter    ap_ST_fsm_state23 = 28'd4194304;
parameter    ap_ST_fsm_state24 = 28'd8388608;
parameter    ap_ST_fsm_state25 = 28'd16777216;
parameter    ap_ST_fsm_state26 = 28'd33554432;
parameter    ap_ST_fsm_state27 = 28'd67108864;
parameter    ap_ST_fsm_state28 = 28'd134217728;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [127:0] m_axi_gmem_WDATA;
output  [15:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [127:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [63:0] in1;
input  [63:0] in2;
output  [31:0] c_ifmap_patch_st_din;
input   c_ifmap_patch_st_full_n;
output   c_ifmap_patch_st_write;
input  [31:0] ctrl1_reg;
input  [31:0] ctrl2_reg;
input  [31:0] layer1_reg;
input  [31:0] layer2_reg;
output  [31:0] ctrl1_reg_c21_din;
input   ctrl1_reg_c21_full_n;
output   ctrl1_reg_c21_write;
output  [31:0] ctrl2_reg_c26_din;
input   ctrl2_reg_c26_full_n;
output   ctrl2_reg_c26_write;
output  [31:0] layer1_reg_c31_din;
input   layer1_reg_c31_full_n;
output   layer1_reg_c31_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg m_axi_gmem_ARVALID;
reg[63:0] m_axi_gmem_ARADDR;
reg[0:0] m_axi_gmem_ARID;
reg[31:0] m_axi_gmem_ARLEN;
reg[2:0] m_axi_gmem_ARSIZE;
reg[1:0] m_axi_gmem_ARBURST;
reg[1:0] m_axi_gmem_ARLOCK;
reg[3:0] m_axi_gmem_ARCACHE;
reg[2:0] m_axi_gmem_ARPROT;
reg[3:0] m_axi_gmem_ARQOS;
reg[3:0] m_axi_gmem_ARREGION;
reg[0:0] m_axi_gmem_ARUSER;
reg m_axi_gmem_RREADY;
reg c_ifmap_patch_st_write;
reg ctrl1_reg_c21_write;
reg ctrl2_reg_c26_write;
reg layer1_reg_c31_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [27:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state19;
reg    ctrl1_reg_c21_blk_n;
reg    ctrl2_reg_c26_blk_n;
reg    layer1_reg_c31_blk_n;
wire   [7:0] empty_177_fu_300_p1;
reg   [7:0] empty_177_reg_737;
wire   [7:0] p_cast6_fu_304_p4;
reg   [7:0] p_cast6_reg_743;
wire   [15:0] p_cast3_cast_fu_314_p1;
reg   [15:0] p_cast3_cast_reg_751;
wire   [15:0] bound_fu_318_p2;
reg   [15:0] bound_reg_756;
wire   [23:0] cast2_fu_324_p1;
wire    ap_CS_fsm_state4;
wire   [8:0] sub_i_i_fu_359_p2;
reg   [8:0] sub_i_i_reg_787;
wire   [16:0] p_cast20_cast_fu_365_p1;
reg   [16:0] p_cast20_cast_reg_792;
wire   [15:0] p_cast_fu_368_p4;
reg   [15:0] p_cast_reg_797;
wire   [16:0] p_cast_cast_fu_378_p1;
reg   [16:0] p_cast_cast_reg_803;
wire   [0:0] cmp_i_i121205_fu_382_p2;
reg   [0:0] cmp_i_i121205_reg_808;
wire   [31:0] zext_ln207_fu_418_p1;
reg   [31:0] zext_ln207_reg_812;
wire   [61:0] add_ln207_1_fu_434_p2;
reg   [61:0] add_ln207_1_reg_818;
wire  signed [31:0] sext_ln192_fu_446_p1;
reg  signed [31:0] sext_ln192_reg_824;
wire  signed [23:0] grp_fu_697_p2;
reg   [23:0] bound4_reg_830;
wire  signed [23:0] grp_fu_703_p2;
reg   [23:0] bound24_reg_835;
wire   [0:0] icmp_ln1057_fu_450_p2;
reg   [0:0] icmp_ln1057_reg_840;
wire   [23:0] add_ln1057_fu_463_p2;
reg   [23:0] add_ln1057_reg_848;
wire    ap_CS_fsm_state5;
wire   [7:0] select_ln188_fu_477_p3;
reg   [7:0] select_ln188_reg_853;
wire   [0:0] icmp_ln1057_12_fu_458_p2;
wire   [0:0] icmp_ln1057_14_fu_489_p2;
reg   [0:0] icmp_ln1057_14_reg_859;
wire   [15:0] mul_ln205_fu_497_p2;
reg   [15:0] mul_ln205_reg_864;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln207_fu_516_p2;
reg   [0:0] icmp_ln207_reg_871;
wire    ap_CS_fsm_state7;
wire   [15:0] trunc_ln207_fu_522_p1;
reg   [15:0] trunc_ln207_reg_875;
wire   [15:0] add_ln207_3_fu_531_p2;
reg   [15:0] add_ln207_3_reg_884;
wire    ap_CS_fsm_state8;
wire   [10:0] tmp_13_cast_fu_541_p3;
reg   [10:0] tmp_13_cast_reg_889;
wire   [0:0] icmp_ln207_1_fu_526_p2;
reg   [59:0] trunc_ln7_reg_894;
wire   [15:0] add_ln217_1_fu_604_p2;
reg   [15:0] add_ln217_1_reg_908;
wire    ap_CS_fsm_state18;
wire   [10:0] tmp_14_cast_fu_614_p3;
reg   [10:0] tmp_14_cast_reg_913;
wire   [0:0] icmp_ln217_fu_599_p2;
reg   [59:0] trunc_ln8_reg_918;
wire   [0:0] rev77_fu_666_p2;
reg   [0:0] rev77_reg_924;
reg   [10:0] burst_buffer1_address0;
reg    burst_buffer1_ce0;
reg    burst_buffer1_we0;
wire   [127:0] burst_buffer1_q0;
reg   [10:0] burst_buffer2_address0;
reg    burst_buffer2_ce0;
reg    burst_buffer2_we0;
wire   [127:0] burst_buffer2_q0;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_ap_start;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_ap_done;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_ap_idle;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_ap_ready;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWVALID;
wire   [63:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWADDR;
wire   [0:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWID;
wire   [31:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWLEN;
wire   [2:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWSIZE;
wire   [1:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWBURST;
wire   [1:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWLOCK;
wire   [3:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWCACHE;
wire   [2:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWPROT;
wire   [3:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWQOS;
wire   [3:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWREGION;
wire   [0:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWUSER;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_WVALID;
wire   [127:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_WDATA;
wire   [15:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_WSTRB;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_WLAST;
wire   [0:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_WID;
wire   [0:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_WUSER;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARVALID;
wire   [63:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARADDR;
wire   [0:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARID;
wire   [31:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARLEN;
wire   [2:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARSIZE;
wire   [1:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARBURST;
wire   [1:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARLOCK;
wire   [3:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARCACHE;
wire   [2:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARPROT;
wire   [3:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARQOS;
wire   [3:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARREGION;
wire   [0:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARUSER;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_RREADY;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_BREADY;
wire   [10:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_burst_buffer1_address0;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_burst_buffer1_ce0;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_burst_buffer1_we0;
wire   [127:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_burst_buffer1_d0;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_start;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_done;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_idle;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_ready;
wire   [31:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_c_ifmap_patch_st_din;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_c_ifmap_patch_st_write;
wire   [10:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_burst_buffer1_address0;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_burst_buffer1_ce0;
wire   [10:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_burst_buffer2_address0;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_burst_buffer2_ce0;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_ap_start;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_ap_done;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_ap_idle;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_ap_ready;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWVALID;
wire   [63:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWADDR;
wire   [0:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWID;
wire   [31:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWLEN;
wire   [2:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWSIZE;
wire   [1:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWBURST;
wire   [1:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWLOCK;
wire   [3:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWCACHE;
wire   [2:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWPROT;
wire   [3:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWQOS;
wire   [3:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWREGION;
wire   [0:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWUSER;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_WVALID;
wire   [127:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_WDATA;
wire   [15:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_WSTRB;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_WLAST;
wire   [0:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_WID;
wire   [0:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_WUSER;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARVALID;
wire   [63:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARADDR;
wire   [0:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARID;
wire   [31:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARLEN;
wire   [2:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARSIZE;
wire   [1:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARBURST;
wire   [1:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARLOCK;
wire   [3:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARCACHE;
wire   [2:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARPROT;
wire   [3:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARQOS;
wire   [3:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARREGION;
wire   [0:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARUSER;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_RREADY;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_BREADY;
wire   [10:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_burst_buffer2_address0;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_burst_buffer2_ce0;
wire    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_burst_buffer2_we0;
wire   [127:0] grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_burst_buffer2_d0;
reg   [15:0] lsy_reg_238;
wire    ap_CS_fsm_state17;
reg    ap_block_state17_on_subcall_done;
reg   [15:0] lsy_1_reg_249;
wire    ap_CS_fsm_state27;
reg    ap_block_state27_on_subcall_done;
reg    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_ap_start_reg;
wire    ap_CS_fsm_state15;
reg   [27:0] ap_NS_fsm;
wire    ap_NS_fsm_state16;
wire    ap_CS_fsm_state16;
reg    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_start_reg;
wire    ap_CS_fsm_state28;
reg    grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_ap_start_reg;
wire    ap_CS_fsm_state25;
wire    ap_NS_fsm_state26;
wire    ap_CS_fsm_state26;
wire  signed [63:0] sext_ln210_1_fu_589_p1;
wire  signed [63:0] sext_ln220_1_fu_687_p1;
reg   [7:0] pny_fu_142;
wire   [7:0] pny_6_fu_673_p2;
reg    ap_block_state1;
reg   [23:0] indvar_flatten27_fu_146;
reg   [31:0] rd_ptr1_fu_150;
wire   [31:0] add_ln207_2_fu_579_p2;
reg   [31:0] rd_ptr2_fu_154;
wire   [31:0] add_ln217_fu_652_p2;
wire   [7:0] bound_fu_318_p0;
wire   [7:0] bound_fu_318_p1;
wire   [15:0] empty_fu_296_p1;
wire   [8:0] ctrl2_reg_load_cast_cast_fu_356_p1;
wire   [16:0] add_ln207_fu_388_p2;
wire  signed [13:0] trunc_ln_fu_394_p4;
wire  signed [28:0] sext_ln210_2_fu_404_p1;
wire   [29:0] zext_ln210_fu_408_p1;
wire   [29:0] add_ln210_fu_412_p2;
wire  signed [60:0] sext_ln207_fu_422_p1;
wire   [61:0] zext_ln207_1_fu_426_p1;
wire  signed [14:0] sext_ln207_1_fu_430_p1;
wire   [14:0] add_ln210_2_fu_440_p2;
wire   [0:0] icmp_ln1057_13_fu_472_p2;
wire   [8:0] zext_ln1057_fu_485_p1;
wire   [7:0] mul_ln205_fu_497_p0;
wire   [7:0] mul_ln205_fu_497_p1;
wire   [16:0] zext_ln205_fu_502_p1;
wire   [16:0] chunk_size_fu_505_p2;
wire   [16:0] chunk_size_1_fu_510_p3;
wire   [5:0] trunc_ln214_fu_537_p1;
wire   [35:0] shl_ln_fu_552_p3;
wire  signed [63:0] sext_ln210_fu_560_p1;
wire   [63:0] add_ln210_1_fu_564_p2;
wire   [5:0] trunc_ln224_fu_610_p1;
wire   [35:0] shl_ln1_fu_625_p3;
wire  signed [63:0] sext_ln220_fu_633_p1;
wire   [63:0] add_ln220_fu_637_p2;
wire   [0:0] ult_fu_662_p2;
wire   [7:0] grp_fu_697_p0;
wire   [15:0] grp_fu_697_p1;
wire   [15:0] grp_fu_703_p0;
wire   [7:0] grp_fu_703_p1;
reg    grp_fu_697_ce;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_fu_703_ce;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
reg    ap_ST_fsm_state27_blk;
reg    ap_ST_fsm_state28_blk;
wire   [23:0] grp_fu_697_p10;
wire   [23:0] grp_fu_703_p00;
wire   [15:0] mul_ln205_fu_497_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 28'd1;
#0 grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_ap_start_reg = 1'b0;
#0 grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_start_reg = 1'b0;
#0 grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_ap_start_reg = 1'b0;
end

fwd_fft_Mem_Patch_Gen_burst_buffer1 #(
    .DataWidth( 128 ),
    .AddressRange( 1984 ),
    .AddressWidth( 11 ))
burst_buffer1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(burst_buffer1_address0),
    .ce0(burst_buffer1_ce0),
    .we0(burst_buffer1_we0),
    .d0(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_burst_buffer1_d0),
    .q0(burst_buffer1_q0)
);

fwd_fft_Mem_Patch_Gen_burst_buffer1 #(
    .DataWidth( 128 ),
    .AddressRange( 1984 ),
    .AddressWidth( 11 ))
burst_buffer2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(burst_buffer2_address0),
    .ce0(burst_buffer2_ce0),
    .we0(burst_buffer2_we0),
    .d0(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_burst_buffer2_d0),
    .q0(burst_buffer2_q0)
);

fwd_fft_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4 grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_ap_start),
    .ap_done(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_ap_done),
    .ap_idle(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_ap_idle),
    .ap_ready(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_ap_ready),
    .m_axi_gmem_AWVALID(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_RVALID),
    .m_axi_gmem_RREADY(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_RID),
    .m_axi_gmem_RUSER(m_axi_gmem_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .sext_ln210_1(trunc_ln7_reg_894),
    .add_ln207_1(add_ln207_1_reg_818),
    .zext_ln214_1(tmp_13_cast_reg_889),
    .burst_buffer1_address0(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_burst_buffer1_address0),
    .burst_buffer1_ce0(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_burst_buffer1_ce0),
    .burst_buffer1_we0(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_burst_buffer1_we0),
    .burst_buffer1_d0(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_burst_buffer1_d0)
);

fwd_fft_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9 grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_start),
    .ap_done(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_done),
    .ap_idle(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_idle),
    .ap_ready(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_ready),
    .c_ifmap_patch_st_din(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_c_ifmap_patch_st_din),
    .c_ifmap_patch_st_full_n(c_ifmap_patch_st_full_n),
    .c_ifmap_patch_st_write(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_c_ifmap_patch_st_write),
    .mul_ln205(mul_ln205_reg_864),
    .p_cast(p_cast_reg_797),
    .bound4(bound4_reg_830),
    .bound(bound_reg_756),
    .p_cast3_cast(p_cast6_reg_743),
    .cmp_i_not_mid115(rev77_reg_924),
    .p_cast6(p_cast6_reg_743),
    .icmp_ln1057(icmp_ln1057_reg_840),
    .burst_buffer1_address0(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_burst_buffer1_address0),
    .burst_buffer1_ce0(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_burst_buffer1_ce0),
    .burst_buffer1_q0(burst_buffer1_q0),
    .burst_buffer2_address0(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_burst_buffer2_address0),
    .burst_buffer2_ce0(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_burst_buffer2_ce0),
    .burst_buffer2_q0(burst_buffer2_q0)
);

fwd_fft_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6 grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_ap_start),
    .ap_done(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_ap_done),
    .ap_idle(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_ap_idle),
    .ap_ready(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_ap_ready),
    .m_axi_gmem_AWVALID(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_RVALID),
    .m_axi_gmem_RREADY(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_RID),
    .m_axi_gmem_RUSER(m_axi_gmem_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .sext_ln220_1(trunc_ln8_reg_918),
    .add_ln207_1(add_ln207_1_reg_818),
    .zext_ln224_1(tmp_14_cast_reg_913),
    .burst_buffer2_address0(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_burst_buffer2_address0),
    .burst_buffer2_ce0(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_burst_buffer2_ce0),
    .burst_buffer2_we0(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_burst_buffer2_we0),
    .burst_buffer2_d0(grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_burst_buffer2_d0)
);

fwd_fft_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U25(
    .din0(bound_fu_318_p0),
    .din1(bound_fu_318_p1),
    .dout(bound_fu_318_p2)
);

fwd_fft_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U26(
    .din0(mul_ln205_fu_497_p0),
    .din1(mul_ln205_fu_497_p1),
    .dout(mul_ln205_fu_497_p2)
);

fwd_fft_mul_mul_8ns_16ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_mul_8ns_16ns_24_4_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_697_p0),
    .din1(grp_fu_697_p1),
    .ce(grp_fu_697_ce),
    .dout(grp_fu_697_p2)
);

fwd_fft_mul_mul_16ns_8ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_mul_16ns_8ns_24_4_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_703_p0),
    .din1(grp_fu_703_p1),
    .ce(grp_fu_703_ce),
    .dout(grp_fu_703_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln1057_12_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state16) & (1'b1 == ap_CS_fsm_state15))) begin
            grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_ap_start_reg <= 1'b1;
        end else if ((grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_ap_ready == 1'b1)) begin
            grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state26) & (1'b1 == ap_CS_fsm_state25))) begin
            grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_ap_start_reg <= 1'b1;
        end else if ((grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_ap_ready == 1'b1)) begin
            grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state18) & ((icmp_ln217_fu_599_p2 == 1'd1) | (icmp_ln207_reg_871 == 1'd0)))) begin
            grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_start_reg <= 1'b1;
        end else if ((grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_ready == 1'b1)) begin
            grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (layer1_reg_c31_full_n == 1'b0) | (ctrl2_reg_c26_full_n == 1'b0) | (ctrl1_reg_c21_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten27_fu_146 <= 24'd0;
    end else if (((1'b1 == ap_CS_fsm_state18) & ((icmp_ln217_fu_599_p2 == 1'd1) | (icmp_ln207_reg_871 == 1'd0)))) begin
        indvar_flatten27_fu_146 <= add_ln1057_reg_848;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln207_1_fu_526_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        lsy_1_reg_249 <= 16'd0;
    end else if (((1'b0 == ap_block_state27_on_subcall_done) & (1'b1 == ap_CS_fsm_state27))) begin
        lsy_1_reg_249 <= add_ln217_1_reg_908;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln207_fu_516_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        lsy_reg_238 <= 16'd0;
    end else if (((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17))) begin
        lsy_reg_238 <= add_ln207_3_reg_884;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (layer1_reg_c31_full_n == 1'b0) | (ctrl2_reg_c26_full_n == 1'b0) | (ctrl1_reg_c21_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        pny_fu_142 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state18) & ((icmp_ln217_fu_599_p2 == 1'd1) | (icmp_ln207_reg_871 == 1'd0)))) begin
        pny_fu_142 <= pny_6_fu_673_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (layer1_reg_c31_full_n == 1'b0) | (ctrl2_reg_c26_full_n == 1'b0) | (ctrl1_reg_c21_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rd_ptr1_fu_150 <= 32'd0;
    end else if (((icmp_ln207_1_fu_526_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (cmp_i_i121205_reg_808 == 1'd1))) begin
        rd_ptr1_fu_150 <= add_ln207_2_fu_579_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (layer1_reg_c31_full_n == 1'b0) | (ctrl2_reg_c26_full_n == 1'b0) | (ctrl1_reg_c21_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rd_ptr2_fu_154 <= 32'd0;
    end else if (((icmp_ln217_fu_599_p2 == 1'd0) & (icmp_ln207_reg_871 == 1'd1) & (1'b1 == ap_CS_fsm_state18) & (cmp_i_i121205_reg_808 == 1'd1))) begin
        rd_ptr2_fu_154 <= add_ln217_fu_652_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln1057_reg_848 <= add_ln1057_fu_463_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln207_1_reg_818 <= add_ln207_1_fu_434_p2;
        bound24_reg_835 <= grp_fu_703_p2;
        bound4_reg_830 <= grp_fu_697_p2;
        cmp_i_i121205_reg_808 <= cmp_i_i121205_fu_382_p2;
        icmp_ln1057_reg_840 <= icmp_ln1057_fu_450_p2;
        p_cast20_cast_reg_792[7 : 0] <= p_cast20_cast_fu_365_p1[7 : 0];
        p_cast_cast_reg_803[15 : 0] <= p_cast_cast_fu_378_p1[15 : 0];
        p_cast_reg_797 <= {{layer2_reg[31:16]}};
        sext_ln192_reg_824 <= sext_ln192_fu_446_p1;
        sub_i_i_reg_787 <= sub_i_i_fu_359_p2;
        zext_ln207_reg_812[29 : 0] <= zext_ln207_fu_418_p1[29 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln207_3_reg_884 <= add_ln207_3_fu_531_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln207_reg_871 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        add_ln217_1_reg_908 <= add_ln217_1_fu_604_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        bound_reg_756 <= bound_fu_318_p2;
        empty_177_reg_737 <= empty_177_fu_300_p1;
        p_cast3_cast_reg_751[7 : 0] <= p_cast3_cast_fu_314_p1[7 : 0];
        p_cast6_reg_743 <= {{ctrl1_reg[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1057_12_fu_458_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        icmp_ln1057_14_reg_859 <= icmp_ln1057_14_fu_489_p2;
        select_ln188_reg_853 <= select_ln188_fu_477_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        icmp_ln207_reg_871 <= icmp_ln207_fu_516_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        mul_ln205_reg_864 <= mul_ln205_fu_497_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) & ((icmp_ln217_fu_599_p2 == 1'd1) | (icmp_ln207_reg_871 == 1'd0)))) begin
        rev77_reg_924 <= rev77_fu_666_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln207_1_fu_526_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        tmp_13_cast_reg_889[10 : 5] <= tmp_13_cast_fu_541_p3[10 : 5];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln217_fu_599_p2 == 1'd0) & (icmp_ln207_reg_871 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        tmp_14_cast_reg_913[10 : 5] <= tmp_14_cast_fu_614_p3[10 : 5];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln207_fu_516_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        trunc_ln207_reg_875 <= trunc_ln207_fu_522_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln207_1_fu_526_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (cmp_i_i121205_reg_808 == 1'd1))) begin
        trunc_ln7_reg_894 <= {{add_ln210_1_fu_564_p2[63:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln217_fu_599_p2 == 1'd0) & (icmp_ln207_reg_871 == 1'd1) & (1'b1 == ap_CS_fsm_state18) & (cmp_i_i121205_reg_808 == 1'd1))) begin
        trunc_ln8_reg_918 <= {{add_ln220_fu_637_p2[63:4]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state17_on_subcall_done)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0) | (layer1_reg_c31_full_n == 1'b0) | (ctrl2_reg_c26_full_n == 1'b0) | (ctrl1_reg_c21_full_n == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state27_on_subcall_done)) begin
        ap_ST_fsm_state27_blk = 1'b1;
    end else begin
        ap_ST_fsm_state27_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_done == 1'b0)) begin
        ap_ST_fsm_state28_blk = 1'b1;
    end else begin
        ap_ST_fsm_state28_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1057_12_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        burst_buffer1_address0 = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_burst_buffer1_address0;
    end else if (((1'b1 == ap_CS_fsm_state17) & (cmp_i_i121205_reg_808 == 1'd1))) begin
        burst_buffer1_address0 = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_burst_buffer1_address0;
    end else begin
        burst_buffer1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        burst_buffer1_ce0 = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_burst_buffer1_ce0;
    end else if (((1'b1 == ap_CS_fsm_state17) & (cmp_i_i121205_reg_808 == 1'd1))) begin
        burst_buffer1_ce0 = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_burst_buffer1_ce0;
    end else begin
        burst_buffer1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (cmp_i_i121205_reg_808 == 1'd1))) begin
        burst_buffer1_we0 = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_burst_buffer1_we0;
    end else begin
        burst_buffer1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state27) & (cmp_i_i121205_reg_808 == 1'd1))) begin
        burst_buffer2_address0 = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_burst_buffer2_address0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        burst_buffer2_address0 = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_burst_buffer2_address0;
    end else begin
        burst_buffer2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state27) & (cmp_i_i121205_reg_808 == 1'd1))) begin
        burst_buffer2_ce0 = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_burst_buffer2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        burst_buffer2_ce0 = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_burst_buffer2_ce0;
    end else begin
        burst_buffer2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state27) & (cmp_i_i121205_reg_808 == 1'd1))) begin
        burst_buffer2_we0 = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_burst_buffer2_we0;
    end else begin
        burst_buffer2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        c_ifmap_patch_st_write = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_c_ifmap_patch_st_write;
    end else begin
        c_ifmap_patch_st_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ctrl1_reg_c21_blk_n = ctrl1_reg_c21_full_n;
    end else begin
        ctrl1_reg_c21_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (layer1_reg_c31_full_n == 1'b0) | (ctrl2_reg_c26_full_n == 1'b0) | (ctrl1_reg_c21_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ctrl1_reg_c21_write = 1'b1;
    end else begin
        ctrl1_reg_c21_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ctrl2_reg_c26_blk_n = ctrl2_reg_c26_full_n;
    end else begin
        ctrl2_reg_c26_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (layer1_reg_c31_full_n == 1'b0) | (ctrl2_reg_c26_full_n == 1'b0) | (ctrl1_reg_c21_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ctrl2_reg_c26_write = 1'b1;
    end else begin
        ctrl2_reg_c26_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state4) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (layer1_reg_c31_full_n == 1'b0) | (ctrl2_reg_c26_full_n == 1'b0) | (ctrl1_reg_c21_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_fu_697_ce = 1'b1;
    end else begin
        grp_fu_697_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state4) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (layer1_reg_c31_full_n == 1'b0) | (ctrl2_reg_c26_full_n == 1'b0) | (ctrl1_reg_c21_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_fu_703_ce = 1'b1;
    end else begin
        grp_fu_703_ce = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1057_12_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer1_reg_c31_blk_n = layer1_reg_c31_full_n;
    end else begin
        layer1_reg_c31_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (layer1_reg_c31_full_n == 1'b0) | (ctrl2_reg_c26_full_n == 1'b0) | (ctrl1_reg_c21_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer1_reg_c31_write = 1'b1;
    end else begin
        layer1_reg_c31_write = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        m_axi_gmem_ARADDR = sext_ln220_1_fu_687_p1;
    end else if (((m_axi_gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_ARADDR = sext_ln210_1_fu_589_p1;
    end else if (((1'b1 == ap_CS_fsm_state26) | ((1'b1 == ap_CS_fsm_state27) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARADDR = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state17) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARADDR = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARADDR;
    end else begin
        m_axi_gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | ((1'b1 == ap_CS_fsm_state27) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARBURST = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARBURST;
    end else if (((1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state17) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARBURST = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARBURST;
    end else begin
        m_axi_gmem_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | ((1'b1 == ap_CS_fsm_state27) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARCACHE = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARCACHE;
    end else if (((1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state17) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARCACHE = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARCACHE;
    end else begin
        m_axi_gmem_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | ((1'b1 == ap_CS_fsm_state27) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARID = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARID;
    end else if (((1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state17) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARID = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARID;
    end else begin
        m_axi_gmem_ARID = 1'd0;
    end
end

always @ (*) begin
    if ((((m_axi_gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19)) | ((m_axi_gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state9)))) begin
        m_axi_gmem_ARLEN = sext_ln192_reg_824;
    end else if (((1'b1 == ap_CS_fsm_state26) | ((1'b1 == ap_CS_fsm_state27) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARLEN = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state17) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARLEN = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARLEN;
    end else begin
        m_axi_gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | ((1'b1 == ap_CS_fsm_state27) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARLOCK = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARLOCK;
    end else if (((1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state17) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARLOCK = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARLOCK;
    end else begin
        m_axi_gmem_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | ((1'b1 == ap_CS_fsm_state27) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARPROT = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARPROT;
    end else if (((1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state17) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARPROT = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARPROT;
    end else begin
        m_axi_gmem_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | ((1'b1 == ap_CS_fsm_state27) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARQOS = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARQOS;
    end else if (((1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state17) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARQOS = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARQOS;
    end else begin
        m_axi_gmem_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | ((1'b1 == ap_CS_fsm_state27) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARREGION = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARREGION;
    end else if (((1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state17) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARREGION = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARREGION;
    end else begin
        m_axi_gmem_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | ((1'b1 == ap_CS_fsm_state27) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARSIZE = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARSIZE;
    end else if (((1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state17) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARSIZE = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARSIZE;
    end else begin
        m_axi_gmem_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | ((1'b1 == ap_CS_fsm_state27) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARUSER = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARUSER;
    end else if (((1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state17) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARUSER = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARUSER;
    end else begin
        m_axi_gmem_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if ((((m_axi_gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19)) | ((m_axi_gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state9)))) begin
        m_axi_gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state26) | ((1'b1 == ap_CS_fsm_state27) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARVALID = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state17) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_ARVALID = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_ARVALID;
    end else begin
        m_axi_gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | ((1'b1 == ap_CS_fsm_state27) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_RREADY = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state17) & (cmp_i_i121205_reg_808 == 1'd1)))) begin
        m_axi_gmem_RREADY = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_m_axi_gmem_RREADY;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (layer1_reg_c31_full_n == 1'b0) | (ctrl2_reg_c26_full_n == 1'b0) | (ctrl1_reg_c21_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln1057_12_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln207_fu_516_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((icmp_ln207_1_fu_526_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else if (((icmp_ln207_1_fu_526_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (cmp_i_i121205_reg_808 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((m_axi_gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((1'b0 == ap_block_state17_on_subcall_done) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((1'b1 == ap_CS_fsm_state18) & ((icmp_ln217_fu_599_p2 == 1'd1) | (icmp_ln207_reg_871 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else if (((icmp_ln217_fu_599_p2 == 1'd0) & (icmp_ln207_reg_871 == 1'd1) & (1'b1 == ap_CS_fsm_state18) & (cmp_i_i121205_reg_808 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((m_axi_gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            if (((1'b0 == ap_block_state27_on_subcall_done) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state28 : begin
            if (((grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1057_fu_463_p2 = (indvar_flatten27_fu_146 + 24'd1);

assign add_ln207_1_fu_434_p2 = (zext_ln207_1_fu_426_p1 + 62'd1);

assign add_ln207_2_fu_579_p2 = (rd_ptr1_fu_150 + zext_ln207_reg_812);

assign add_ln207_3_fu_531_p2 = (lsy_reg_238 + 16'd1);

assign add_ln207_fu_388_p2 = ($signed(p_cast_cast_fu_378_p1) + $signed(17'd131071));

assign add_ln210_1_fu_564_p2 = ($signed(sext_ln210_fu_560_p1) + $signed(in1));

assign add_ln210_2_fu_440_p2 = ($signed(sext_ln207_1_fu_430_p1) + $signed(15'd1));

assign add_ln210_fu_412_p2 = (zext_ln210_fu_408_p1 + 30'd1);

assign add_ln217_1_fu_604_p2 = (lsy_1_reg_249 + 16'd1);

assign add_ln217_fu_652_p2 = (rd_ptr2_fu_154 + zext_ln207_reg_812);

assign add_ln220_fu_637_p2 = ($signed(sext_ln220_fu_633_p1) + $signed(in2));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state16 = ap_NS_fsm[32'd15];

assign ap_NS_fsm_state26 = ap_NS_fsm[32'd25];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0) | (layer1_reg_c31_full_n == 1'b0) | (ctrl2_reg_c26_full_n == 1'b0) | (ctrl1_reg_c21_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state17_on_subcall_done = ((grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_ap_done == 1'b0) & (cmp_i_i121205_reg_808 == 1'd1));
end

always @ (*) begin
    ap_block_state27_on_subcall_done = ((grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_ap_done == 1'b0) & (cmp_i_i121205_reg_808 == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign bound_fu_318_p0 = p_cast3_cast_fu_314_p1;

assign bound_fu_318_p1 = p_cast3_cast_fu_314_p1;

assign c_ifmap_patch_st_din = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_c_ifmap_patch_st_din;

assign cast2_fu_324_p1 = empty_177_fu_300_p1;

assign chunk_size_1_fu_510_p3 = ((icmp_ln1057_14_reg_859[0:0] == 1'b1) ? p_cast20_cast_reg_792 : chunk_size_fu_505_p2);

assign chunk_size_fu_505_p2 = (p_cast_cast_reg_803 - zext_ln205_fu_502_p1);

assign cmp_i_i121205_fu_382_p2 = ((p_cast_fu_368_p4 != 16'd0) ? 1'b1 : 1'b0);

assign ctrl1_reg_c21_din = ctrl1_reg;

assign ctrl2_reg_c26_din = ctrl2_reg;

assign ctrl2_reg_load_cast_cast_fu_356_p1 = empty_177_reg_737;

assign empty_177_fu_300_p1 = ctrl2_reg[7:0];

assign empty_fu_296_p1 = layer1_reg[15:0];

assign grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_ap_start = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_210_4_fu_260_ap_start_reg;

assign grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_ap_start = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_220_6_fu_286_ap_start_reg;

assign grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_start = grp_Mem_Patch_Gen_Pipeline_VITIS_LOOP_228_7_VITIS_LOOP_231_8_VITIS_LOOP_234_9_fu_270_ap_start_reg;

assign grp_fu_697_p0 = cast2_fu_324_p1;

assign grp_fu_697_p1 = grp_fu_697_p10;

assign grp_fu_697_p10 = bound_fu_318_p2;

assign grp_fu_703_p0 = grp_fu_703_p00;

assign grp_fu_703_p00 = empty_fu_296_p1;

assign grp_fu_703_p1 = cast2_fu_324_p1;

assign icmp_ln1057_12_fu_458_p2 = ((indvar_flatten27_fu_146 == bound24_reg_835) ? 1'b1 : 1'b0);

assign icmp_ln1057_13_fu_472_p2 = ((pny_fu_142 == empty_177_reg_737) ? 1'b1 : 1'b0);

assign icmp_ln1057_14_fu_489_p2 = (($signed(zext_ln1057_fu_485_p1) < $signed(sub_i_i_reg_787)) ? 1'b1 : 1'b0);

assign icmp_ln1057_fu_450_p2 = ((p_cast6_reg_743 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln207_1_fu_526_p2 = ((lsy_reg_238 == trunc_ln207_reg_875) ? 1'b1 : 1'b0);

assign icmp_ln207_fu_516_p2 = (($signed(chunk_size_1_fu_510_p3) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln217_fu_599_p2 = ((lsy_1_reg_249 == trunc_ln207_reg_875) ? 1'b1 : 1'b0);

assign layer1_reg_c31_din = layer1_reg;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_WDATA = 128'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 16'd0;

assign m_axi_gmem_WUSER = 1'd0;

assign m_axi_gmem_WVALID = 1'b0;

assign mul_ln205_fu_497_p0 = mul_ln205_fu_497_p00;

assign mul_ln205_fu_497_p00 = select_ln188_reg_853;

assign mul_ln205_fu_497_p1 = p_cast3_cast_reg_751;

assign p_cast20_cast_fu_365_p1 = p_cast6_reg_743;

assign p_cast3_cast_fu_314_p1 = p_cast6_fu_304_p4;

assign p_cast6_fu_304_p4 = {{ctrl1_reg[31:24]}};

assign p_cast_cast_fu_378_p1 = p_cast_fu_368_p4;

assign p_cast_fu_368_p4 = {{layer2_reg[31:16]}};

assign pny_6_fu_673_p2 = (select_ln188_reg_853 + 8'd1);

assign rev77_fu_666_p2 = (ult_fu_662_p2 ^ 1'd1);

assign select_ln188_fu_477_p3 = ((icmp_ln1057_13_fu_472_p2[0:0] == 1'b1) ? 8'd0 : pny_fu_142);

assign sext_ln192_fu_446_p1 = $signed(add_ln210_2_fu_440_p2);

assign sext_ln207_1_fu_430_p1 = trunc_ln_fu_394_p4;

assign sext_ln207_fu_422_p1 = trunc_ln_fu_394_p4;

assign sext_ln210_1_fu_589_p1 = $signed(trunc_ln7_reg_894);

assign sext_ln210_2_fu_404_p1 = trunc_ln_fu_394_p4;

assign sext_ln210_fu_560_p1 = $signed(shl_ln_fu_552_p3);

assign sext_ln220_1_fu_687_p1 = $signed(trunc_ln8_reg_918);

assign sext_ln220_fu_633_p1 = $signed(shl_ln1_fu_625_p3);

assign shl_ln1_fu_625_p3 = {{rd_ptr2_fu_154}, {4'd0}};

assign shl_ln_fu_552_p3 = {{rd_ptr1_fu_150}, {4'd0}};

assign start_out = real_start;

assign sub_i_i_fu_359_p2 = ($signed(ctrl2_reg_load_cast_cast_fu_356_p1) + $signed(9'd511));

assign tmp_13_cast_fu_541_p3 = {{trunc_ln214_fu_537_p1}, {5'd0}};

assign tmp_14_cast_fu_614_p3 = {{trunc_ln224_fu_610_p1}, {5'd0}};

assign trunc_ln207_fu_522_p1 = chunk_size_1_fu_510_p3[15:0];

assign trunc_ln214_fu_537_p1 = lsy_reg_238[5:0];

assign trunc_ln224_fu_610_p1 = lsy_1_reg_249[5:0];

assign trunc_ln_fu_394_p4 = {{add_ln207_fu_388_p2[16:3]}};

assign ult_fu_662_p2 = ((mul_ln205_reg_864 < p_cast_reg_797) ? 1'b1 : 1'b0);

assign zext_ln1057_fu_485_p1 = select_ln188_fu_477_p3;

assign zext_ln205_fu_502_p1 = mul_ln205_reg_864;

assign zext_ln207_1_fu_426_p1 = $unsigned(sext_ln207_fu_422_p1);

assign zext_ln207_fu_418_p1 = add_ln210_fu_412_p2;

assign zext_ln210_fu_408_p1 = $unsigned(sext_ln210_2_fu_404_p1);

always @ (posedge ap_clk) begin
    p_cast3_cast_reg_751[15:8] <= 8'b00000000;
    p_cast20_cast_reg_792[16:8] <= 9'b000000000;
    p_cast_cast_reg_803[16] <= 1'b0;
    zext_ln207_reg_812[31:30] <= 2'b00;
    tmp_13_cast_reg_889[4:0] <= 5'b00000;
    tmp_14_cast_reg_913[4:0] <= 5'b00000;
end

endmodule //fwd_fft_Mem_Patch_Gen
