// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module IFFT_AP_fft_stage_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        I_address0,
        I_ce0,
        I_q0,
        I_address1,
        I_ce1,
        I_q1,
        X_0_0_address0,
        X_0_0_ce0,
        X_0_0_we0,
        X_0_0_d0,
        X_0_1_address0,
        X_0_1_ce0,
        X_0_1_we0,
        X_0_1_d0,
        X_1_0_address0,
        X_1_0_ce0,
        X_1_0_we0,
        X_1_0_d0,
        X_1_1_address0,
        X_1_1_ce0,
        X_1_1_we0,
        X_1_1_d0,
        p_read,
        ap_return
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [11:0] I_address0;
output   I_ce0;
input  [31:0] I_q0;
output  [11:0] I_address1;
output   I_ce1;
input  [31:0] I_q1;
output  [9:0] X_0_0_address0;
output   X_0_0_ce0;
output   X_0_0_we0;
output  [31:0] X_0_0_d0;
output  [9:0] X_0_1_address0;
output   X_0_1_ce0;
output   X_0_1_we0;
output  [31:0] X_0_1_d0;
output  [9:0] X_1_0_address0;
output   X_1_0_ce0;
output   X_1_0_we0;
output  [31:0] X_1_0_d0;
output  [9:0] X_1_1_address0;
output   X_1_1_ce0;
output   X_1_1_we0;
output  [31:0] X_1_1_d0;
input  [31:0] p_read;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[11:0] I_address0;
reg I_ce0;
reg[11:0] I_address1;
reg I_ce1;
reg[9:0] X_0_0_address0;
reg X_0_0_ce0;
reg X_0_0_we0;
reg[31:0] X_0_0_d0;
reg[9:0] X_0_1_address0;
reg X_0_1_ce0;
reg X_0_1_we0;
reg[31:0] X_0_1_d0;
reg[9:0] X_1_0_address0;
reg X_1_0_ce0;
reg X_1_0_we0;
reg[31:0] X_1_0_d0;
reg[9:0] X_1_1_address0;
reg X_1_1_ce0;
reg X_1_1_we0;
reg[31:0] X_1_1_d0;
reg[31:0] ap_return;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln1039_fu_102_p2;
reg   [0:0] icmp_ln1039_reg_171;
wire   [7:0] empty_fu_108_p1;
reg   [7:0] empty_reg_175;
reg   [6:0] tmp_reg_181;
wire   [69:0] mul_ln63_fu_138_p2;
reg   [69:0] mul_ln63_reg_186;
wire    ap_CS_fsm_state2;
wire   [6:0] trunc_ln1_fu_145_p4;
reg   [6:0] trunc_ln1_reg_191;
wire    ap_CS_fsm_state4;
wire   [13:0] bound_fu_159_p2;
reg   [13:0] bound_reg_196;
wire    grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_ap_start;
wire    grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_ap_done;
wire    grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_ap_idle;
wire    grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_ap_ready;
wire   [11:0] grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_I_address0;
wire    grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_I_ce0;
wire   [11:0] grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_I_address1;
wire    grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_I_ce1;
wire   [9:0] grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_0_address0;
wire    grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_0_ce0;
wire    grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_0_we0;
wire   [31:0] grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_0_d0;
wire   [9:0] grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_1_address0;
wire    grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_1_ce0;
wire    grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_1_we0;
wire   [31:0] grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_1_d0;
wire   [9:0] grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_0_address0;
wire    grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_0_ce0;
wire    grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_0_we0;
wire   [31:0] grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_0_d0;
wire   [9:0] grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_1_address0;
wire    grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_1_ce0;
wire    grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_1_we0;
wire   [31:0] grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_1_d0;
wire    grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_ap_start;
wire    grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_ap_done;
wire    grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_ap_idle;
wire    grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_ap_ready;
wire   [11:0] grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_I_address0;
wire    grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_I_ce0;
wire   [11:0] grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_I_address1;
wire    grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_I_ce1;
wire   [9:0] grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_0_address0;
wire    grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_0_ce0;
wire    grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_0_we0;
wire   [31:0] grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_0_d0;
wire   [9:0] grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_1_address0;
wire    grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_1_ce0;
wire    grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_1_we0;
wire   [31:0] grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_1_d0;
wire   [9:0] grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_0_address0;
wire    grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_0_ce0;
wire    grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_0_we0;
wire   [31:0] grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_0_d0;
wire   [9:0] grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_1_address0;
wire    grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_1_ce0;
wire    grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_1_we0;
wire   [31:0] grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_1_d0;
reg    grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_ap_start_reg;
reg    ap_block_state1;
wire   [7:0] trunc_ln_fu_92_p4;
wire   [8:0] zext_ln63_fu_112_p1;
wire   [8:0] add_ln63_fu_116_p2;
wire   [7:0] mul_ln63_fu_138_p0;
wire   [6:0] mul_ln63_fu_138_p1;
wire   [6:0] bound_fu_159_p0;
wire   [13:0] cast_fu_155_p1;
wire   [6:0] bound_fu_159_p1;
reg   [31:0] ap_return_preg;
reg    ap_block_state3_on_subcall_done;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire   [69:0] mul_ln63_fu_138_p00;
wire   [69:0] mul_ln63_fu_138_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_ap_start_reg = 1'b0;
#0 grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_ap_start_reg = 1'b0;
#0 ap_return_preg = 32'd0;
end

IFFT_AP_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2 grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_ap_start),
    .ap_done(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_ap_done),
    .ap_idle(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_ap_idle),
    .ap_ready(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_ap_ready),
    .mul_ln63(mul_ln63_reg_186),
    .zext_ln63(empty_reg_175),
    .I_address0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_I_address0),
    .I_ce0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_I_ce0),
    .I_q0(I_q0),
    .I_address1(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_I_address1),
    .I_ce1(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_I_ce1),
    .I_q1(I_q1),
    .X_0_0_address0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_0_address0),
    .X_0_0_ce0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_0_ce0),
    .X_0_0_we0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_0_we0),
    .X_0_0_d0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_0_d0),
    .X_0_1_address0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_1_address0),
    .X_0_1_ce0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_1_ce0),
    .X_0_1_we0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_1_we0),
    .X_0_1_d0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_1_d0),
    .X_1_0_address0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_0_address0),
    .X_1_0_ce0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_0_ce0),
    .X_1_0_we0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_0_we0),
    .X_1_0_d0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_0_d0),
    .X_1_1_address0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_1_address0),
    .X_1_1_ce0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_1_ce0),
    .X_1_1_we0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_1_we0),
    .X_1_1_d0(grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_1_d0)
);

IFFT_AP_fft_stage_5_Pipeline_SKIP_X_SKIP_Y grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_ap_start),
    .ap_done(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_ap_done),
    .ap_idle(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_ap_idle),
    .ap_ready(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_ap_ready),
    .bound(bound_reg_196),
    .trunc_ln10(trunc_ln1_reg_191),
    .I_address0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_I_address0),
    .I_ce0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_I_ce0),
    .I_q0(I_q0),
    .I_address1(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_I_address1),
    .I_ce1(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_I_ce1),
    .I_q1(I_q1),
    .X_0_0_address0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_0_address0),
    .X_0_0_ce0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_0_ce0),
    .X_0_0_we0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_0_we0),
    .X_0_0_d0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_0_d0),
    .X_0_1_address0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_1_address0),
    .X_0_1_ce0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_1_ce0),
    .X_0_1_we0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_1_we0),
    .X_0_1_d0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_1_d0),
    .X_1_0_address0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_0_address0),
    .X_1_0_ce0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_0_ce0),
    .X_1_0_we0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_0_we0),
    .X_1_0_d0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_0_d0),
    .X_1_1_address0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_1_address0),
    .X_1_1_ce0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_1_ce0),
    .X_1_1_we0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_1_we0),
    .X_1_1_d0(grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_1_d0)
);

IFFT_AP_mul_8ns_7ns_70_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 70 ))
mul_8ns_7ns_70_1_1_U232(
    .din0(mul_ln63_fu_138_p0),
    .din1(mul_ln63_fu_138_p1),
    .dout(mul_ln63_fu_138_p2)
);

IFFT_AP_mul_7ns_7ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 14 ))
mul_7ns_7ns_14_1_1_U233(
    .din0(bound_fu_159_p0),
    .din1(bound_fu_159_p1),
    .dout(bound_fu_159_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_return_preg <= p_read;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_ap_start_reg <= 1'b1;
        end else if ((grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_ap_ready == 1'b1)) begin
            grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_ap_start_reg <= 1'b1;
        end else if ((grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_ap_ready == 1'b1)) begin
            grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bound_reg_196 <= bound_fu_159_p2;
        trunc_ln1_reg_191 <= {{p_read[7:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_reg_175 <= empty_fu_108_p1;
        icmp_ln1039_reg_171 <= icmp_ln1039_fu_102_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mul_ln63_reg_186 <= mul_ln63_fu_138_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1039_fu_102_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_reg_181 <= {{add_ln63_fu_116_p2[8:2]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            I_address0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_I_address0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            I_address0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_I_address0;
        end else begin
            I_address0 = 'bx;
        end
    end else begin
        I_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            I_address1 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_I_address1;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            I_address1 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_I_address1;
        end else begin
            I_address1 = 'bx;
        end
    end else begin
        I_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            I_ce0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_I_ce0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            I_ce0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_I_ce0;
        end else begin
            I_ce0 = 1'b0;
        end
    end else begin
        I_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            I_ce1 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_I_ce1;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            I_ce1 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_I_ce1;
        end else begin
            I_ce1 = 1'b0;
        end
    end else begin
        I_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            X_0_0_address0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_0_address0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            X_0_0_address0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_0_address0;
        end else begin
            X_0_0_address0 = 'bx;
        end
    end else begin
        X_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            X_0_0_ce0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_0_ce0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            X_0_0_ce0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_0_ce0;
        end else begin
            X_0_0_ce0 = 1'b0;
        end
    end else begin
        X_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            X_0_0_d0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_0_d0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            X_0_0_d0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_0_d0;
        end else begin
            X_0_0_d0 = 'bx;
        end
    end else begin
        X_0_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            X_0_0_we0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_0_we0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            X_0_0_we0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_0_we0;
        end else begin
            X_0_0_we0 = 1'b0;
        end
    end else begin
        X_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            X_0_1_address0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_1_address0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            X_0_1_address0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_1_address0;
        end else begin
            X_0_1_address0 = 'bx;
        end
    end else begin
        X_0_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            X_0_1_ce0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_1_ce0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            X_0_1_ce0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_1_ce0;
        end else begin
            X_0_1_ce0 = 1'b0;
        end
    end else begin
        X_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            X_0_1_d0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_1_d0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            X_0_1_d0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_1_d0;
        end else begin
            X_0_1_d0 = 'bx;
        end
    end else begin
        X_0_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            X_0_1_we0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_0_1_we0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            X_0_1_we0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_0_1_we0;
        end else begin
            X_0_1_we0 = 1'b0;
        end
    end else begin
        X_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            X_1_0_address0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_0_address0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            X_1_0_address0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_0_address0;
        end else begin
            X_1_0_address0 = 'bx;
        end
    end else begin
        X_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            X_1_0_ce0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_0_ce0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            X_1_0_ce0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_0_ce0;
        end else begin
            X_1_0_ce0 = 1'b0;
        end
    end else begin
        X_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            X_1_0_d0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_0_d0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            X_1_0_d0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_0_d0;
        end else begin
            X_1_0_d0 = 'bx;
        end
    end else begin
        X_1_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            X_1_0_we0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_0_we0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            X_1_0_we0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_0_we0;
        end else begin
            X_1_0_we0 = 1'b0;
        end
    end else begin
        X_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            X_1_1_address0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_1_address0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            X_1_1_address0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_1_address0;
        end else begin
            X_1_1_address0 = 'bx;
        end
    end else begin
        X_1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            X_1_1_ce0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_1_ce0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            X_1_1_ce0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_1_ce0;
        end else begin
            X_1_1_ce0 = 1'b0;
        end
    end else begin
        X_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            X_1_1_d0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_1_d0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            X_1_1_d0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_1_d0;
        end else begin
            X_1_1_d0 = 'bx;
        end
    end else begin
        X_1_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln1039_reg_171 == 1'd1)) begin
            X_1_1_we0 = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_X_1_1_we0;
        end else if ((icmp_ln1039_reg_171 == 1'd0)) begin
            X_1_1_we0 = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_X_1_1_we0;
        end else begin
            X_1_1_we0 = 1'b0;
        end
    end else begin
        X_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_return = p_read;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (icmp_ln1039_fu_102_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (icmp_ln1039_fu_102_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln63_fu_116_p2 = (zext_ln63_fu_112_p1 + 9'd3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state3_on_subcall_done = (((grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_ap_done == 1'b0) & (icmp_ln1039_reg_171 == 1'd0)) | ((icmp_ln1039_reg_171 == 1'd1) & (grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_ap_done == 1'b0)));
end

assign bound_fu_159_p0 = cast_fu_155_p1;

assign bound_fu_159_p1 = cast_fu_155_p1;

assign cast_fu_155_p1 = trunc_ln1_fu_145_p4;

assign empty_fu_108_p1 = p_read[7:0];

assign grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_ap_start = grp_fft_stage_5_Pipeline_SKIP_X_SKIP_Y_fu_72_ap_start_reg;

assign grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_ap_start = grp_fft_stage_5_Pipeline_VITIS_LOOP_63_1_VITIS_LOOP_66_2_fu_56_ap_start_reg;

assign icmp_ln1039_fu_102_p2 = ((trunc_ln_fu_92_p4 > 8'd5) ? 1'b1 : 1'b0);

assign mul_ln63_fu_138_p0 = mul_ln63_fu_138_p00;

assign mul_ln63_fu_138_p00 = empty_reg_175;

assign mul_ln63_fu_138_p1 = mul_ln63_fu_138_p10;

assign mul_ln63_fu_138_p10 = tmp_reg_181;

assign trunc_ln1_fu_145_p4 = {{p_read[7:1]}};

assign trunc_ln_fu_92_p4 = {{p_read[15:8]}};

assign zext_ln63_fu_112_p1 = empty_fu_108_p1;

endmodule //IFFT_AP_fft_stage_5
