// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module IFFT_AP_fft_stage_4_Pipeline_SKIP_X_SKIP_Y (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bound,
        trunc_ln14,
        I_address0,
        I_ce0,
        I_q0,
        I_address1,
        I_ce1,
        I_q1,
        X_address0,
        X_ce0,
        X_we0,
        X_d0,
        X_address1,
        X_ce1,
        X_we1,
        X_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [13:0] bound;
input  [6:0] trunc_ln14;
output  [11:0] I_address0;
output   I_ce0;
input  [31:0] I_q0;
output  [11:0] I_address1;
output   I_ce1;
input  [31:0] I_q1;
output  [11:0] X_address0;
output   X_ce0;
output   X_we0;
output  [31:0] X_d0;
output  [11:0] X_address1;
output   X_ce1;
output   X_we1;
output  [31:0] X_d1;

reg ap_idle;
reg[11:0] I_address0;
reg I_ce0;
reg[11:0] I_address1;
reg I_ce1;
reg[11:0] X_address0;
reg X_ce0;
reg X_we0;
reg[31:0] X_d0;
reg[11:0] X_address1;
reg X_ce1;
reg X_we1;
reg[31:0] X_d1;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_state6_pp0_stage1_iter2;
wire    ap_block_state8_pp0_stage1_iter3;
wire    ap_block_state10_pp0_stage1_iter4;
wire    ap_block_state12_pp0_stage1_iter5;
wire    ap_block_state14_pp0_stage1_iter6;
wire    ap_block_state16_pp0_stage1_iter7;
wire    ap_block_state18_pp0_stage1_iter8;
wire    ap_block_state20_pp0_stage1_iter9;
wire    ap_block_state22_pp0_stage1_iter10;
wire    ap_block_state24_pp0_stage1_iter11;
wire    ap_block_state26_pp0_stage1_iter12;
wire    ap_block_pp0_stage1_subdone;
wire   [0:0] icmp_ln1027_fu_413_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [4:0] w_8_address0;
reg    w_8_ce0;
wire   [15:0] w_8_q0;
wire   [4:0] w_8_address1;
reg    w_8_ce1;
wire   [15:0] w_8_q1;
reg   [4:0] w_13_address0;
reg    w_13_ce0;
wire   [15:0] w_13_q0;
wire   [4:0] w_13_address1;
reg    w_13_ce1;
wire   [15:0] w_13_q1;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state9_pp0_stage0_iter4;
wire    ap_block_state11_pp0_stage0_iter5;
wire    ap_block_state13_pp0_stage0_iter6;
wire    ap_block_state15_pp0_stage0_iter7;
wire    ap_block_state17_pp0_stage0_iter8;
wire    ap_block_state19_pp0_stage0_iter9;
wire    ap_block_state21_pp0_stage0_iter10;
wire    ap_block_state23_pp0_stage0_iter11;
wire    ap_block_state25_pp0_stage0_iter12;
wire    ap_block_state27_pp0_stage0_iter13;
wire    ap_block_pp0_stage0_11001;
wire   [5:0] add40_fu_407_p2;
reg   [5:0] add40_reg_913;
wire    ap_block_pp0_stage1_11001;
reg   [0:0] icmp_ln1027_reg_918;
reg   [0:0] icmp_ln1027_reg_918_pp0_iter1_reg;
reg   [0:0] icmp_ln1027_reg_918_pp0_iter2_reg;
reg   [0:0] icmp_ln1027_reg_918_pp0_iter3_reg;
reg   [0:0] icmp_ln1027_reg_918_pp0_iter4_reg;
reg   [0:0] icmp_ln1027_reg_918_pp0_iter5_reg;
reg   [0:0] icmp_ln1027_reg_918_pp0_iter6_reg;
reg   [0:0] icmp_ln1027_reg_918_pp0_iter7_reg;
reg   [0:0] icmp_ln1027_reg_918_pp0_iter8_reg;
reg   [0:0] icmp_ln1027_reg_918_pp0_iter9_reg;
reg   [0:0] icmp_ln1027_reg_918_pp0_iter10_reg;
reg   [0:0] icmp_ln1027_reg_918_pp0_iter11_reg;
wire   [0:0] icmp_ln1027_7_fu_483_p2;
reg   [0:0] icmp_ln1027_7_reg_922;
wire   [31:0] select_ln1027_8_fu_488_p3;
reg   [31:0] select_ln1027_8_reg_929;
wire   [3:0] trunc_ln1027_11_fu_496_p1;
reg   [3:0] trunc_ln1027_11_reg_934;
wire   [5:0] add40_mid1_fu_508_p2;
reg   [5:0] add40_mid1_reg_939;
wire   [31:0] select_ln1027_7_fu_569_p3;
reg   [31:0] select_ln1027_7_reg_944;
wire   [5:0] select_ln1027_9_fu_576_p3;
reg   [5:0] select_ln1027_9_reg_949;
wire   [5:0] add_ln1027_1_fu_581_p2;
reg   [5:0] add_ln1027_1_reg_954;
wire   [3:0] add_ln28_fu_604_p2;
reg   [3:0] add_ln28_reg_969;
wire   [11:0] add_ln29_fu_609_p2;
reg   [11:0] add_ln29_reg_974;
wire   [11:0] add_ln30_fu_615_p2;
reg   [11:0] add_ln30_reg_980;
reg   [15:0] w_8_load_reg_986;
reg   [15:0] w_13_load_reg_992;
wire   [63:0] zext_ln388_fu_711_p1;
reg   [63:0] zext_ln388_reg_1008;
reg   [63:0] zext_ln388_reg_1008_pp0_iter2_reg;
reg   [63:0] zext_ln388_reg_1008_pp0_iter3_reg;
reg   [63:0] zext_ln388_reg_1008_pp0_iter4_reg;
reg   [63:0] zext_ln388_reg_1008_pp0_iter5_reg;
reg   [63:0] zext_ln388_reg_1008_pp0_iter6_reg;
reg   [63:0] zext_ln388_reg_1008_pp0_iter7_reg;
reg   [63:0] zext_ln388_reg_1008_pp0_iter8_reg;
reg   [63:0] zext_ln388_reg_1008_pp0_iter9_reg;
reg   [63:0] zext_ln388_reg_1008_pp0_iter10_reg;
reg   [63:0] zext_ln388_reg_1008_pp0_iter11_reg;
reg   [63:0] zext_ln388_reg_1008_pp0_iter12_reg;
wire   [11:0] add_ln328_fu_716_p2;
reg   [11:0] add_ln328_reg_1018;
reg   [11:0] add_ln328_reg_1018_pp0_iter2_reg;
reg   [11:0] add_ln328_reg_1018_pp0_iter3_reg;
reg   [11:0] add_ln328_reg_1018_pp0_iter4_reg;
reg   [11:0] add_ln328_reg_1018_pp0_iter5_reg;
wire   [63:0] zext_ln388_7_fu_726_p1;
reg   [63:0] zext_ln388_7_reg_1023;
reg   [63:0] zext_ln388_7_reg_1023_pp0_iter2_reg;
reg   [63:0] zext_ln388_7_reg_1023_pp0_iter3_reg;
reg   [63:0] zext_ln388_7_reg_1023_pp0_iter4_reg;
reg   [63:0] zext_ln388_7_reg_1023_pp0_iter5_reg;
reg   [63:0] zext_ln388_7_reg_1023_pp0_iter6_reg;
reg   [63:0] zext_ln388_7_reg_1023_pp0_iter7_reg;
reg   [63:0] zext_ln388_7_reg_1023_pp0_iter8_reg;
reg   [63:0] zext_ln388_7_reg_1023_pp0_iter9_reg;
reg   [63:0] zext_ln388_7_reg_1023_pp0_iter10_reg;
reg   [63:0] zext_ln388_7_reg_1023_pp0_iter11_reg;
wire   [11:0] add_ln388_4_fu_731_p2;
reg   [11:0] add_ln388_4_reg_1033;
reg   [15:0] w2_M_real_reg_1038;
reg   [15:0] w2_M_imag_reg_1044;
wire   [15:0] p_r_M_real_fu_745_p1;
reg   [15:0] p_r_M_real_reg_1060;
wire   [15:0] p_r_M_imag_fu_749_p1;
reg   [15:0] p_r_M_imag_reg_1066;
wire   [63:0] zext_ln388_8_fu_753_p1;
reg   [63:0] zext_ln388_8_reg_1072;
reg   [63:0] zext_ln388_8_reg_1072_pp0_iter3_reg;
reg   [63:0] zext_ln388_8_reg_1072_pp0_iter4_reg;
reg   [63:0] zext_ln388_8_reg_1072_pp0_iter5_reg;
reg   [63:0] zext_ln388_8_reg_1072_pp0_iter6_reg;
reg   [63:0] zext_ln388_8_reg_1072_pp0_iter7_reg;
reg   [63:0] zext_ln388_8_reg_1072_pp0_iter8_reg;
reg   [63:0] zext_ln388_8_reg_1072_pp0_iter9_reg;
reg   [63:0] zext_ln388_8_reg_1072_pp0_iter10_reg;
reg   [63:0] zext_ln388_8_reg_1072_pp0_iter11_reg;
reg   [63:0] zext_ln388_8_reg_1072_pp0_iter12_reg;
wire   [15:0] p_r_M_real_40_fu_761_p1;
reg   [15:0] p_r_M_real_40_reg_1082;
wire   [15:0] p_r_M_imag_44_fu_765_p1;
reg   [15:0] p_r_M_imag_44_reg_1088;
reg   [15:0] w12_M_real_reg_1094;
reg   [15:0] w12_M_imag_reg_1100;
wire   [15:0] p_r_M_real_42_fu_773_p1;
reg   [15:0] p_r_M_real_42_reg_1106;
wire   [15:0] p_r_M_imag_46_fu_777_p1;
reg   [15:0] p_r_M_imag_46_reg_1112;
wire   [15:0] grp_fu_316_p2;
reg   [15:0] mul_i_i_reg_1118;
wire   [15:0] grp_fu_320_p2;
reg   [15:0] mul3_i_i_reg_1123;
wire   [15:0] grp_fu_324_p2;
reg   [15:0] mul6_i_i_reg_1128;
wire   [15:0] grp_fu_328_p2;
reg   [15:0] mul9_i_i_reg_1133;
wire   [15:0] grp_fu_332_p2;
reg   [15:0] mul_i_i3_reg_1138;
wire   [15:0] grp_fu_336_p2;
reg   [15:0] mul3_i_i3_reg_1143;
reg   [15:0] mul6_i_i3_reg_1148;
reg   [15:0] mul9_i_i3_reg_1153;
reg   [15:0] mul_i_i4_reg_1158;
reg   [15:0] mul3_i_i4_reg_1163;
reg   [15:0] mul6_i_i4_reg_1168;
reg   [15:0] mul9_i_i4_reg_1173;
wire   [63:0] zext_ln328_fu_781_p1;
reg   [63:0] zext_ln328_reg_1178;
reg   [63:0] zext_ln328_reg_1178_pp0_iter7_reg;
reg   [63:0] zext_ln328_reg_1178_pp0_iter8_reg;
reg   [63:0] zext_ln328_reg_1178_pp0_iter9_reg;
reg   [63:0] zext_ln328_reg_1178_pp0_iter10_reg;
reg   [63:0] zext_ln328_reg_1178_pp0_iter11_reg;
reg   [63:0] zext_ln328_reg_1178_pp0_iter12_reg;
wire   [15:0] grp_fu_288_p2;
reg   [15:0] p_r_reg_1188;
wire   [15:0] grp_fu_260_p2;
reg   [15:0] p_r_M_imag_50_reg_1194;
wire   [15:0] grp_fu_292_p2;
reg   [15:0] p_r_5_reg_1200;
wire   [15:0] p_r_M_real_44_fu_789_p1;
reg   [15:0] p_r_M_real_44_reg_1206;
wire   [15:0] p_r_M_imag_48_fu_793_p1;
reg   [15:0] p_r_M_imag_48_reg_1212;
reg   [15:0] p_r_M_imag_60_reg_1218;
reg   [15:0] p_r_6_reg_1224;
wire   [15:0] grp_fu_264_p2;
reg   [15:0] p_r_M_imag_61_reg_1230;
wire   [15:0] grp_fu_268_p2;
reg   [15:0] p_r_M_real_53_reg_1236;
reg   [15:0] p_r_M_real_51_reg_1242;
reg   [15:0] p_r_M_real_51_reg_1242_pp0_iter10_reg;
reg   [15:0] p_r_M_imag_57_reg_1248;
reg   [15:0] p_r_M_real_56_reg_1254;
wire   [15:0] grp_fu_272_p2;
reg   [15:0] p_r_M_imag_62_reg_1260;
wire   [15:0] grp_fu_296_p2;
reg   [15:0] p_r_M_imag_55_reg_1266;
wire   [15:0] grp_fu_300_p2;
reg   [15:0] p_r_M_real_57_reg_1272;
wire   [15:0] grp_fu_304_p2;
reg   [15:0] p_r_M_imag_63_reg_1278;
wire   [31:0] add3_i_i290_partset_fu_805_p3;
reg   [31:0] add3_i_i290_partset_reg_1284;
wire   [31:0] add3_i_i294_partset_fu_821_p3;
reg   [31:0] add3_i_i294_partset_reg_1289;
wire   [31:0] sub3_i_i298_partset_fu_837_p3;
reg   [31:0] sub3_i_i298_partset_reg_1294;
wire   [31:0] sub3_i_i302_partset_fu_853_p3;
reg   [31:0] sub3_i_i302_partset_reg_1299;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln1027_fu_587_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln27_fu_701_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln28_fu_736_p1;
reg   [6:0] k2_fu_76;
wire   [6:0] k2_4_fu_528_p3;
wire    ap_loop_init;
reg   [31:0] j2_fu_80;
wire   [31:0] j2_6_fu_661_p3;
reg   [31:0] m2_fu_84;
wire   [31:0] m2_4_fu_669_p3;
reg   [31:0] j1_fu_88;
reg   [31:0] m1_fu_92;
wire   [31:0] select_ln1027_10_fu_514_p3;
reg   [13:0] indvar_flatten_fu_96;
wire   [13:0] add_ln1027_fu_418_p2;
reg   [15:0] grp_fu_260_p0;
reg   [15:0] grp_fu_260_p1;
reg   [15:0] grp_fu_264_p0;
reg   [15:0] grp_fu_264_p1;
reg   [15:0] grp_fu_268_p0;
reg   [15:0] grp_fu_268_p1;
reg   [15:0] grp_fu_272_p0;
reg   [15:0] grp_fu_272_p1;
reg   [15:0] grp_fu_288_p0;
reg   [15:0] grp_fu_288_p1;
reg   [15:0] grp_fu_292_p0;
reg   [15:0] grp_fu_292_p1;
reg   [15:0] grp_fu_296_p0;
reg   [15:0] grp_fu_296_p1;
reg   [15:0] grp_fu_300_p0;
reg   [15:0] grp_fu_300_p1;
reg   [15:0] grp_fu_316_p0;
reg   [15:0] grp_fu_316_p1;
reg   [15:0] grp_fu_320_p0;
reg   [15:0] grp_fu_320_p1;
reg   [15:0] grp_fu_324_p0;
reg   [15:0] grp_fu_324_p1;
reg   [15:0] grp_fu_328_p0;
reg   [15:0] grp_fu_328_p1;
reg   [15:0] grp_fu_332_p0;
reg   [15:0] grp_fu_332_p1;
reg   [15:0] grp_fu_336_p0;
reg   [15:0] grp_fu_336_p1;
wire   [5:0] trunc_ln1027_10_fu_403_p1;
wire   [5:0] trunc_ln1027_fu_399_p1;
wire   [0:0] icmp_ln54_fu_439_p2;
wire   [31:0] add_ln57_fu_445_p2;
wire   [0:0] icmp_ln50_fu_427_p2;
wire   [31:0] j1_12_fu_433_p2;
wire   [31:0] j1_13_fu_451_p3;
wire   [31:0] m1_8_fu_459_p3;
wire   [31:0] j1_14_fu_467_p3;
wire   [31:0] m1_9_fu_475_p3;
wire   [5:0] trunc_ln1027_13_fu_504_p1;
wire   [5:0] trunc_ln1027_12_fu_500_p1;
wire   [6:0] add_ln22_fu_522_p2;
wire   [31:0] select_ln1027_fu_562_p3;
wire   [3:0] trunc_ln1027_16_fu_600_p1;
wire   [11:0] trunc_ln1027_15_fu_596_p1;
wire   [11:0] trunc_ln1027_14_fu_592_p1;
wire   [0:0] icmp_ln44_fu_633_p2;
wire   [31:0] add_ln47_fu_639_p2;
wire   [0:0] icmp_ln40_fu_621_p2;
wire   [31:0] j2_4_fu_627_p2;
wire   [31:0] j2_5_fu_645_p3;
wire   [31:0] m2_3_fu_653_p3;
wire   [11:0] tmp_fu_687_p3;
wire   [11:0] add_ln388_fu_706_p2;
wire   [11:0] tmp_s_fu_694_p3;
wire   [11:0] add_ln388_3_fu_721_p2;
wire   [15:0] trunc_ln388_fu_741_p1;
wire   [15:0] grp_fu_340_p4;
wire   [15:0] trunc_ln388_9_fu_757_p1;
wire   [15:0] grp_fu_350_p4;
wire   [15:0] trunc_ln388_10_fu_769_p1;
wire   [15:0] trunc_ln328_fu_785_p1;
wire   [15:0] grp_fu_276_p2;
wire   [15:0] bitcast_ln36_2_fu_801_p1;
wire   [15:0] bitcast_ln36_fu_797_p1;
wire   [15:0] grp_fu_280_p2;
wire   [15:0] grp_fu_284_p2;
wire   [15:0] bitcast_ln37_2_fu_817_p1;
wire   [15:0] bitcast_ln37_fu_813_p1;
wire   [15:0] bitcast_ln38_2_fu_833_p1;
wire   [15:0] bitcast_ln38_fu_829_p1;
wire   [15:0] grp_fu_308_p2;
wire   [15:0] grp_fu_312_p2;
wire   [15:0] bitcast_ln39_2_fu_849_p1;
wire   [15:0] bitcast_ln39_fu_845_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter12_stage0;
reg    ap_idle_pp0_0to11;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to13;
reg    ap_done_pending_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

IFFT_AP_fft_stage_4_Pipeline_SKIP_X_SKIP_Y_w_8_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
w_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w_8_address0),
    .ce0(w_8_ce0),
    .q0(w_8_q0),
    .address1(w_8_address1),
    .ce1(w_8_ce1),
    .q1(w_8_q1)
);

IFFT_AP_fft_stage_4_Pipeline_SKIP_X_SKIP_Y_w_13_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
w_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w_13_address0),
    .ce0(w_13_ce0),
    .q0(w_13_q0),
    .address1(w_13_address1),
    .ce1(w_13_ce1),
    .q1(w_13_q1)
);

IFFT_AP_hadd_16ns_16ns_16_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_5_full_dsp_1_U174(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_260_p0),
    .din1(grp_fu_260_p1),
    .ce(1'b1),
    .dout(grp_fu_260_p2)
);

IFFT_AP_hadd_16ns_16ns_16_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_5_full_dsp_1_U175(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_264_p0),
    .din1(grp_fu_264_p1),
    .ce(1'b1),
    .dout(grp_fu_264_p2)
);

IFFT_AP_hadd_16ns_16ns_16_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_5_full_dsp_1_U176(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_268_p0),
    .din1(grp_fu_268_p1),
    .ce(1'b1),
    .dout(grp_fu_268_p2)
);

IFFT_AP_hadd_16ns_16ns_16_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_5_full_dsp_1_U177(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_272_p0),
    .din1(grp_fu_272_p1),
    .ce(1'b1),
    .dout(grp_fu_272_p2)
);

IFFT_AP_hadd_16ns_16ns_16_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_5_full_dsp_1_U178(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_r_M_imag_57_reg_1248),
    .din1(p_r_M_imag_62_reg_1260),
    .ce(1'b1),
    .dout(grp_fu_276_p2)
);

IFFT_AP_hadd_16ns_16ns_16_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_5_full_dsp_1_U179(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_r_M_real_51_reg_1242),
    .din1(p_r_M_real_57_reg_1272),
    .ce(1'b1),
    .dout(grp_fu_280_p2)
);

IFFT_AP_hadd_16ns_16ns_16_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_5_full_dsp_1_U180(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_r_M_imag_55_reg_1266),
    .din1(p_r_M_imag_63_reg_1278),
    .ce(1'b1),
    .dout(grp_fu_284_p2)
);

IFFT_AP_hsub_16ns_16ns_16_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hsub_16ns_16ns_16_5_full_dsp_1_U181(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_288_p0),
    .din1(grp_fu_288_p1),
    .ce(1'b1),
    .dout(grp_fu_288_p2)
);

IFFT_AP_hsub_16ns_16ns_16_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hsub_16ns_16ns_16_5_full_dsp_1_U182(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_292_p0),
    .din1(grp_fu_292_p1),
    .ce(1'b1),
    .dout(grp_fu_292_p2)
);

IFFT_AP_hsub_16ns_16ns_16_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hsub_16ns_16ns_16_5_full_dsp_1_U183(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_296_p0),
    .din1(grp_fu_296_p1),
    .ce(1'b1),
    .dout(grp_fu_296_p2)
);

IFFT_AP_hsub_16ns_16ns_16_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hsub_16ns_16ns_16_5_full_dsp_1_U184(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_300_p0),
    .din1(grp_fu_300_p1),
    .ce(1'b1),
    .dout(grp_fu_300_p2)
);

IFFT_AP_hsub_16ns_16ns_16_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hsub_16ns_16ns_16_5_full_dsp_1_U185(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_r_M_imag_50_reg_1194),
    .din1(p_r_M_imag_61_reg_1230),
    .ce(1'b1),
    .dout(grp_fu_304_p2)
);

IFFT_AP_hsub_16ns_16ns_16_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hsub_16ns_16ns_16_5_full_dsp_1_U186(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_r_M_real_51_reg_1242_pp0_iter10_reg),
    .din1(p_r_M_real_57_reg_1272),
    .ce(1'b1),
    .dout(grp_fu_308_p2)
);

IFFT_AP_hsub_16ns_16ns_16_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hsub_16ns_16ns_16_5_full_dsp_1_U187(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_r_M_imag_55_reg_1266),
    .din1(p_r_M_imag_63_reg_1278),
    .ce(1'b1),
    .dout(grp_fu_312_p2)
);

IFFT_AP_hmul_16ns_16ns_16_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hmul_16ns_16ns_16_4_max_dsp_1_U188(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_316_p0),
    .din1(grp_fu_316_p1),
    .ce(1'b1),
    .dout(grp_fu_316_p2)
);

IFFT_AP_hmul_16ns_16ns_16_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hmul_16ns_16ns_16_4_max_dsp_1_U189(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_320_p0),
    .din1(grp_fu_320_p1),
    .ce(1'b1),
    .dout(grp_fu_320_p2)
);

IFFT_AP_hmul_16ns_16ns_16_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hmul_16ns_16ns_16_4_max_dsp_1_U190(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_324_p0),
    .din1(grp_fu_324_p1),
    .ce(1'b1),
    .dout(grp_fu_324_p2)
);

IFFT_AP_hmul_16ns_16ns_16_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hmul_16ns_16ns_16_4_max_dsp_1_U191(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_328_p0),
    .din1(grp_fu_328_p1),
    .ce(1'b1),
    .dout(grp_fu_328_p2)
);

IFFT_AP_hmul_16ns_16ns_16_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hmul_16ns_16ns_16_4_max_dsp_1_U192(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_332_p0),
    .din1(grp_fu_332_p1),
    .ce(1'b1),
    .dout(grp_fu_332_p2)
);

IFFT_AP_hmul_16ns_16ns_16_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hmul_16ns_16ns_16_4_max_dsp_1_U193(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_336_p0),
    .din1(grp_fu_336_p1),
    .ce(1'b1),
    .dout(grp_fu_336_p2)
);

IFFT_AP_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter12_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter13 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to11 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter12_stage0))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to11 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter12_stage0))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to11 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter12_stage0))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to11 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter12_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to11 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter12_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to11 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter12_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to11 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter12_stage0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to11 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter12_stage0))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to11 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter12_stage0))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to11 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter12_stage0))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to11 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter12_stage0))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to11 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter12_stage0))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_fu_96 <= 14'd0;
    end else if (((icmp_ln1027_fu_413_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        indvar_flatten_fu_96 <= add_ln1027_fu_418_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j1_fu_88 <= 32'd0;
    end else if (((icmp_ln1027_fu_413_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        j1_fu_88 <= select_ln1027_8_fu_488_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j2_fu_80 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1027_reg_918 == 1'd0))) begin
            j2_fu_80 <= j2_6_fu_661_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k2_fu_76 <= 7'd0;
    end else if (((icmp_ln1027_fu_413_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        k2_fu_76 <= k2_4_fu_528_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m1_fu_92 <= 32'd0;
    end else if (((icmp_ln1027_fu_413_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        m1_fu_92 <= select_ln1027_10_fu_514_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m2_fu_84 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1027_reg_918 == 1'd0))) begin
            m2_fu_84 <= m2_4_fu_669_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add3_i_i290_partset_reg_1284 <= add3_i_i290_partset_fu_805_p3;
        add3_i_i294_partset_reg_1289 <= add3_i_i294_partset_fu_821_p3;
        p_r_M_imag_44_reg_1088 <= p_r_M_imag_44_fu_765_p1;
        p_r_M_imag_reg_1066 <= p_r_M_imag_fu_749_p1;
        p_r_M_real_40_reg_1082 <= p_r_M_real_40_fu_761_p1;
        p_r_M_real_51_reg_1242_pp0_iter10_reg <= p_r_M_real_51_reg_1242;
        p_r_M_real_reg_1060 <= p_r_M_real_fu_745_p1;
        sub3_i_i298_partset_reg_1294 <= sub3_i_i298_partset_fu_837_p3;
        zext_ln328_reg_1178[11 : 0] <= zext_ln328_fu_781_p1[11 : 0];
        zext_ln328_reg_1178_pp0_iter10_reg[11 : 0] <= zext_ln328_reg_1178_pp0_iter9_reg[11 : 0];
        zext_ln328_reg_1178_pp0_iter11_reg[11 : 0] <= zext_ln328_reg_1178_pp0_iter10_reg[11 : 0];
        zext_ln328_reg_1178_pp0_iter12_reg[11 : 0] <= zext_ln328_reg_1178_pp0_iter11_reg[11 : 0];
        zext_ln328_reg_1178_pp0_iter7_reg[11 : 0] <= zext_ln328_reg_1178[11 : 0];
        zext_ln328_reg_1178_pp0_iter8_reg[11 : 0] <= zext_ln328_reg_1178_pp0_iter7_reg[11 : 0];
        zext_ln328_reg_1178_pp0_iter9_reg[11 : 0] <= zext_ln328_reg_1178_pp0_iter8_reg[11 : 0];
        zext_ln388_8_reg_1072[11 : 0] <= zext_ln388_8_fu_753_p1[11 : 0];
        zext_ln388_8_reg_1072_pp0_iter10_reg[11 : 0] <= zext_ln388_8_reg_1072_pp0_iter9_reg[11 : 0];
        zext_ln388_8_reg_1072_pp0_iter11_reg[11 : 0] <= zext_ln388_8_reg_1072_pp0_iter10_reg[11 : 0];
        zext_ln388_8_reg_1072_pp0_iter12_reg[11 : 0] <= zext_ln388_8_reg_1072_pp0_iter11_reg[11 : 0];
        zext_ln388_8_reg_1072_pp0_iter3_reg[11 : 0] <= zext_ln388_8_reg_1072[11 : 0];
        zext_ln388_8_reg_1072_pp0_iter4_reg[11 : 0] <= zext_ln388_8_reg_1072_pp0_iter3_reg[11 : 0];
        zext_ln388_8_reg_1072_pp0_iter5_reg[11 : 0] <= zext_ln388_8_reg_1072_pp0_iter4_reg[11 : 0];
        zext_ln388_8_reg_1072_pp0_iter6_reg[11 : 0] <= zext_ln388_8_reg_1072_pp0_iter5_reg[11 : 0];
        zext_ln388_8_reg_1072_pp0_iter7_reg[11 : 0] <= zext_ln388_8_reg_1072_pp0_iter6_reg[11 : 0];
        zext_ln388_8_reg_1072_pp0_iter8_reg[11 : 0] <= zext_ln388_8_reg_1072_pp0_iter7_reg[11 : 0];
        zext_ln388_8_reg_1072_pp0_iter9_reg[11 : 0] <= zext_ln388_8_reg_1072_pp0_iter8_reg[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_fu_413_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add40_mid1_reg_939 <= add40_mid1_fu_508_p2;
        icmp_ln1027_7_reg_922 <= icmp_ln1027_7_fu_483_p2;
        select_ln1027_8_reg_929 <= select_ln1027_8_fu_488_p3;
        trunc_ln1027_11_reg_934 <= trunc_ln1027_11_fu_496_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add40_reg_913 <= add40_fu_407_p2;
        add_ln328_reg_1018 <= add_ln328_fu_716_p2;
        add_ln328_reg_1018_pp0_iter2_reg <= add_ln328_reg_1018;
        add_ln328_reg_1018_pp0_iter3_reg <= add_ln328_reg_1018_pp0_iter2_reg;
        add_ln328_reg_1018_pp0_iter4_reg <= add_ln328_reg_1018_pp0_iter3_reg;
        add_ln328_reg_1018_pp0_iter5_reg <= add_ln328_reg_1018_pp0_iter4_reg;
        add_ln388_4_reg_1033 <= add_ln388_4_fu_731_p2;
        icmp_ln1027_reg_918 <= icmp_ln1027_fu_413_p2;
        icmp_ln1027_reg_918_pp0_iter10_reg <= icmp_ln1027_reg_918_pp0_iter9_reg;
        icmp_ln1027_reg_918_pp0_iter11_reg <= icmp_ln1027_reg_918_pp0_iter10_reg;
        icmp_ln1027_reg_918_pp0_iter1_reg <= icmp_ln1027_reg_918;
        icmp_ln1027_reg_918_pp0_iter2_reg <= icmp_ln1027_reg_918_pp0_iter1_reg;
        icmp_ln1027_reg_918_pp0_iter3_reg <= icmp_ln1027_reg_918_pp0_iter2_reg;
        icmp_ln1027_reg_918_pp0_iter4_reg <= icmp_ln1027_reg_918_pp0_iter3_reg;
        icmp_ln1027_reg_918_pp0_iter5_reg <= icmp_ln1027_reg_918_pp0_iter4_reg;
        icmp_ln1027_reg_918_pp0_iter6_reg <= icmp_ln1027_reg_918_pp0_iter5_reg;
        icmp_ln1027_reg_918_pp0_iter7_reg <= icmp_ln1027_reg_918_pp0_iter6_reg;
        icmp_ln1027_reg_918_pp0_iter8_reg <= icmp_ln1027_reg_918_pp0_iter7_reg;
        icmp_ln1027_reg_918_pp0_iter9_reg <= icmp_ln1027_reg_918_pp0_iter8_reg;
        p_r_M_imag_46_reg_1112 <= p_r_M_imag_46_fu_777_p1;
        p_r_M_imag_48_reg_1212 <= p_r_M_imag_48_fu_793_p1;
        p_r_M_imag_63_reg_1278 <= grp_fu_304_p2;
        p_r_M_real_42_reg_1106 <= p_r_M_real_42_fu_773_p1;
        p_r_M_real_44_reg_1206 <= p_r_M_real_44_fu_789_p1;
        sub3_i_i302_partset_reg_1299 <= sub3_i_i302_partset_fu_853_p3;
        zext_ln388_7_reg_1023[11 : 0] <= zext_ln388_7_fu_726_p1[11 : 0];
        zext_ln388_7_reg_1023_pp0_iter10_reg[11 : 0] <= zext_ln388_7_reg_1023_pp0_iter9_reg[11 : 0];
        zext_ln388_7_reg_1023_pp0_iter11_reg[11 : 0] <= zext_ln388_7_reg_1023_pp0_iter10_reg[11 : 0];
        zext_ln388_7_reg_1023_pp0_iter2_reg[11 : 0] <= zext_ln388_7_reg_1023[11 : 0];
        zext_ln388_7_reg_1023_pp0_iter3_reg[11 : 0] <= zext_ln388_7_reg_1023_pp0_iter2_reg[11 : 0];
        zext_ln388_7_reg_1023_pp0_iter4_reg[11 : 0] <= zext_ln388_7_reg_1023_pp0_iter3_reg[11 : 0];
        zext_ln388_7_reg_1023_pp0_iter5_reg[11 : 0] <= zext_ln388_7_reg_1023_pp0_iter4_reg[11 : 0];
        zext_ln388_7_reg_1023_pp0_iter6_reg[11 : 0] <= zext_ln388_7_reg_1023_pp0_iter5_reg[11 : 0];
        zext_ln388_7_reg_1023_pp0_iter7_reg[11 : 0] <= zext_ln388_7_reg_1023_pp0_iter6_reg[11 : 0];
        zext_ln388_7_reg_1023_pp0_iter8_reg[11 : 0] <= zext_ln388_7_reg_1023_pp0_iter7_reg[11 : 0];
        zext_ln388_7_reg_1023_pp0_iter9_reg[11 : 0] <= zext_ln388_7_reg_1023_pp0_iter8_reg[11 : 0];
        zext_ln388_reg_1008[11 : 0] <= zext_ln388_fu_711_p1[11 : 0];
        zext_ln388_reg_1008_pp0_iter10_reg[11 : 0] <= zext_ln388_reg_1008_pp0_iter9_reg[11 : 0];
        zext_ln388_reg_1008_pp0_iter11_reg[11 : 0] <= zext_ln388_reg_1008_pp0_iter10_reg[11 : 0];
        zext_ln388_reg_1008_pp0_iter12_reg[11 : 0] <= zext_ln388_reg_1008_pp0_iter11_reg[11 : 0];
        zext_ln388_reg_1008_pp0_iter2_reg[11 : 0] <= zext_ln388_reg_1008[11 : 0];
        zext_ln388_reg_1008_pp0_iter3_reg[11 : 0] <= zext_ln388_reg_1008_pp0_iter2_reg[11 : 0];
        zext_ln388_reg_1008_pp0_iter4_reg[11 : 0] <= zext_ln388_reg_1008_pp0_iter3_reg[11 : 0];
        zext_ln388_reg_1008_pp0_iter5_reg[11 : 0] <= zext_ln388_reg_1008_pp0_iter4_reg[11 : 0];
        zext_ln388_reg_1008_pp0_iter6_reg[11 : 0] <= zext_ln388_reg_1008_pp0_iter5_reg[11 : 0];
        zext_ln388_reg_1008_pp0_iter7_reg[11 : 0] <= zext_ln388_reg_1008_pp0_iter6_reg[11 : 0];
        zext_ln388_reg_1008_pp0_iter8_reg[11 : 0] <= zext_ln388_reg_1008_pp0_iter7_reg[11 : 0];
        zext_ln388_reg_1008_pp0_iter9_reg[11 : 0] <= zext_ln388_reg_1008_pp0_iter8_reg[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1027_reg_918 == 1'd0))) begin
        add_ln1027_1_reg_954 <= add_ln1027_1_fu_581_p2;
        add_ln28_reg_969 <= add_ln28_fu_604_p2;
        add_ln29_reg_974 <= add_ln29_fu_609_p2;
        add_ln30_reg_980 <= add_ln30_fu_615_p2;
        select_ln1027_7_reg_944 <= select_ln1027_7_fu_569_p3;
        select_ln1027_9_reg_949 <= select_ln1027_9_fu_576_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul3_i_i3_reg_1143 <= grp_fu_336_p2;
        mul3_i_i_reg_1123 <= grp_fu_320_p2;
        mul6_i_i_reg_1128 <= grp_fu_324_p2;
        mul9_i_i_reg_1133 <= grp_fu_328_p2;
        mul_i_i3_reg_1138 <= grp_fu_332_p2;
        mul_i_i_reg_1118 <= grp_fu_316_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul3_i_i4_reg_1163 <= grp_fu_328_p2;
        mul6_i_i3_reg_1148 <= grp_fu_316_p2;
        mul6_i_i4_reg_1168 <= grp_fu_332_p2;
        mul9_i_i3_reg_1153 <= grp_fu_320_p2;
        mul9_i_i4_reg_1173 <= grp_fu_336_p2;
        mul_i_i4_reg_1158 <= grp_fu_324_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_r_5_reg_1200 <= grp_fu_292_p2;
        p_r_M_imag_50_reg_1194 <= grp_fu_260_p2;
        p_r_reg_1188 <= grp_fu_288_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_r_6_reg_1224 <= grp_fu_288_p2;
        p_r_M_imag_60_reg_1218 <= grp_fu_260_p2;
        p_r_M_imag_61_reg_1230 <= grp_fu_264_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_r_M_imag_55_reg_1266 <= grp_fu_296_p2;
        p_r_M_imag_57_reg_1248 <= grp_fu_264_p2;
        p_r_M_imag_62_reg_1260 <= grp_fu_272_p2;
        p_r_M_real_56_reg_1254 <= grp_fu_268_p2;
        p_r_M_real_57_reg_1272 <= grp_fu_300_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_r_M_real_51_reg_1242 <= grp_fu_292_p2;
        p_r_M_real_53_reg_1236 <= grp_fu_268_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        w12_M_imag_reg_1100 <= w_13_q0;
        w12_M_real_reg_1094 <= w_8_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w2_M_imag_reg_1044 <= w_13_q0;
        w2_M_real_reg_1038 <= w_8_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        w_13_load_reg_992 <= w_13_q1;
        w_8_load_reg_986 <= w_8_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        I_address0 = zext_ln328_fu_781_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        I_address0 = zext_ln388_7_fu_726_p1;
    end else begin
        I_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        I_address1 = zext_ln388_8_fu_753_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        I_address1 = zext_ln388_fu_711_p1;
    end else begin
        I_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        I_ce0 = 1'b1;
    end else begin
        I_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        I_ce1 = 1'b1;
    end else begin
        I_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_address0 = zext_ln388_8_reg_1072_pp0_iter12_reg;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_address0 = zext_ln388_7_reg_1023_pp0_iter11_reg;
    end else begin
        X_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_address1 = zext_ln388_reg_1008_pp0_iter12_reg;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_address1 = zext_ln328_reg_1178_pp0_iter12_reg;
    end else begin
        X_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        X_ce0 = 1'b1;
    end else begin
        X_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        X_ce1 = 1'b1;
    end else begin
        X_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_d0 = sub3_i_i302_partset_reg_1299;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_d0 = add3_i_i294_partset_reg_1289;
    end else begin
        X_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_d1 = sub3_i_i298_partset_reg_1294;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        X_d1 = add3_i_i290_partset_reg_1284;
    end else begin
        X_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        X_we0 = 1'b1;
    end else begin
        X_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        X_we1 = 1'b1;
    end else begin
        X_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1027_fu_413_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1027_reg_918_pp0_iter11_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter12_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter12_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter12_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready_pp0_iter12_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to11 = 1'b1;
    end else begin
        ap_idle_pp0_0to11 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to13 = 1'b1;
    end else begin
        ap_idle_pp0_1to13 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_260_p0 = mul6_i_i3_reg_1148;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_260_p0 = mul6_i_i_reg_1128;
    end else begin
        grp_fu_260_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_260_p1 = mul9_i_i3_reg_1153;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_260_p1 = mul9_i_i_reg_1133;
    end else begin
        grp_fu_260_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_264_p0 = p_r_M_imag_48_reg_1212;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_264_p0 = mul6_i_i4_reg_1168;
    end else begin
        grp_fu_264_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_264_p1 = p_r_M_imag_60_reg_1218;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_264_p1 = mul9_i_i4_reg_1173;
    end else begin
        grp_fu_264_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_268_p0 = p_r_reg_1188;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_268_p0 = p_r_M_real_44_reg_1206;
        end else begin
            grp_fu_268_p0 = 'bx;
        end
    end else begin
        grp_fu_268_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_268_p1 = p_r_6_reg_1224;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_268_p1 = p_r_5_reg_1200;
        end else begin
            grp_fu_268_p1 = 'bx;
        end
    end else begin
        grp_fu_268_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_272_p0 = p_r_M_real_53_reg_1236;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_272_p0 = p_r_M_imag_50_reg_1194;
    end else begin
        grp_fu_272_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_272_p1 = p_r_M_real_56_reg_1254;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_272_p1 = p_r_M_imag_61_reg_1230;
    end else begin
        grp_fu_272_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_288_p0 = mul_i_i4_reg_1158;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_288_p0 = mul_i_i_reg_1118;
    end else begin
        grp_fu_288_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_288_p1 = mul3_i_i4_reg_1163;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_288_p1 = mul3_i_i_reg_1123;
    end else begin
        grp_fu_288_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_292_p0 = p_r_M_real_44_reg_1206;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_292_p0 = mul_i_i3_reg_1138;
    end else begin
        grp_fu_292_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_292_p1 = p_r_5_reg_1200;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_292_p1 = mul3_i_i3_reg_1143;
    end else begin
        grp_fu_292_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_296_p0 = p_r_M_real_53_reg_1236;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_296_p0 = p_r_M_imag_48_reg_1212;
    end else begin
        grp_fu_296_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_296_p1 = p_r_M_real_56_reg_1254;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_296_p1 = p_r_M_imag_60_reg_1218;
    end else begin
        grp_fu_296_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_300_p0 = p_r_M_imag_57_reg_1248;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_300_p0 = p_r_reg_1188;
    end else begin
        grp_fu_300_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_300_p1 = p_r_M_imag_62_reg_1260;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_300_p1 = p_r_6_reg_1224;
    end else begin
        grp_fu_300_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_316_p0 = p_r_M_real_40_reg_1082;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_316_p0 = p_r_M_real_reg_1060;
    end else begin
        grp_fu_316_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_316_p1 = w2_M_imag_reg_1044;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_316_p1 = w_8_load_reg_986;
    end else begin
        grp_fu_316_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_320_p0 = p_r_M_imag_44_reg_1088;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_320_p0 = p_r_M_imag_reg_1066;
    end else begin
        grp_fu_320_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_320_p1 = w2_M_real_reg_1038;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_320_p1 = w_13_load_reg_992;
    end else begin
        grp_fu_320_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_324_p0 = p_r_M_real_42_reg_1106;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_324_p0 = p_r_M_real_reg_1060;
    end else begin
        grp_fu_324_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_324_p1 = w12_M_real_reg_1094;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_324_p1 = w_13_load_reg_992;
    end else begin
        grp_fu_324_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_328_p0 = p_r_M_imag_46_reg_1112;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_328_p0 = p_r_M_imag_reg_1066;
    end else begin
        grp_fu_328_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_328_p1 = w12_M_imag_reg_1100;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_328_p1 = w_8_load_reg_986;
    end else begin
        grp_fu_328_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_332_p0 = p_r_M_real_42_reg_1106;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_332_p0 = p_r_M_real_40_reg_1082;
    end else begin
        grp_fu_332_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_332_p1 = w12_M_imag_reg_1100;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_332_p1 = w2_M_real_reg_1038;
    end else begin
        grp_fu_332_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_336_p0 = p_r_M_imag_46_reg_1112;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_336_p0 = p_r_M_imag_44_reg_1088;
    end else begin
        grp_fu_336_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_336_p1 = w12_M_real_reg_1094;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_336_p1 = w2_M_imag_reg_1044;
    end else begin
        grp_fu_336_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_13_address0 = zext_ln28_fu_736_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        w_13_address0 = zext_ln27_fu_701_p1;
    end else begin
        w_13_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        w_13_ce0 = 1'b1;
    end else begin
        w_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_13_ce1 = 1'b1;
    end else begin
        w_13_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_8_address0 = zext_ln28_fu_736_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        w_8_address0 = zext_ln27_fu_701_p1;
    end else begin
        w_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        w_8_ce0 = 1'b1;
    end else begin
        w_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_8_ce1 = 1'b1;
    end else begin
        w_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to11 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter12_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to13 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add3_i_i290_partset_fu_805_p3 = {{bitcast_ln36_2_fu_801_p1}, {bitcast_ln36_fu_797_p1}};

assign add3_i_i294_partset_fu_821_p3 = {{bitcast_ln37_2_fu_817_p1}, {bitcast_ln37_fu_813_p1}};

assign add40_fu_407_p2 = (trunc_ln1027_10_fu_403_p1 + trunc_ln1027_fu_399_p1);

assign add40_mid1_fu_508_p2 = (trunc_ln1027_13_fu_504_p1 + trunc_ln1027_12_fu_500_p1);

assign add_ln1027_1_fu_581_p2 = (select_ln1027_9_fu_576_p3 + 6'd16);

assign add_ln1027_fu_418_p2 = (indvar_flatten_fu_96 + 14'd1);

assign add_ln22_fu_522_p2 = (k2_fu_76 + 7'd1);

assign add_ln28_fu_604_p2 = (trunc_ln1027_16_fu_600_p1 + trunc_ln1027_11_reg_934);

assign add_ln29_fu_609_p2 = (trunc_ln1027_15_fu_596_p1 + trunc_ln1027_14_fu_592_p1);

assign add_ln30_fu_615_p2 = (add_ln29_fu_609_p2 + 12'd16);

assign add_ln328_fu_716_p2 = (tmp_s_fu_694_p3 + add_ln29_reg_974);

assign add_ln388_3_fu_721_p2 = (tmp_s_fu_694_p3 + add_ln30_reg_980);

assign add_ln388_4_fu_731_p2 = (tmp_fu_687_p3 + add_ln30_reg_980);

assign add_ln388_fu_706_p2 = (tmp_fu_687_p3 + add_ln29_reg_974);

assign add_ln47_fu_639_p2 = (select_ln1027_fu_562_p3 + 32'd32);

assign add_ln57_fu_445_p2 = (m1_fu_92 + 32'd32);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage1_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage1_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage1_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage1_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage1_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign bitcast_ln36_2_fu_801_p1 = grp_fu_276_p2;

assign bitcast_ln36_fu_797_p1 = grp_fu_272_p2;

assign bitcast_ln37_2_fu_817_p1 = grp_fu_284_p2;

assign bitcast_ln37_fu_813_p1 = grp_fu_280_p2;

assign bitcast_ln38_2_fu_833_p1 = grp_fu_300_p2;

assign bitcast_ln38_fu_829_p1 = grp_fu_296_p2;

assign bitcast_ln39_2_fu_849_p1 = grp_fu_312_p2;

assign bitcast_ln39_fu_845_p1 = grp_fu_308_p2;

assign grp_fu_340_p4 = {{I_q1[31:16]}};

assign grp_fu_350_p4 = {{I_q0[31:16]}};

assign icmp_ln1027_7_fu_483_p2 = ((k2_fu_76 == trunc_ln14) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_413_p2 = ((indvar_flatten_fu_96 == bound) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_621_p2 = ((select_ln1027_7_fu_569_p3 < 32'd15) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_633_p2 = ((select_ln1027_7_fu_569_p3 == 32'd15) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_427_p2 = ((j1_fu_88 < 32'd15) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_439_p2 = ((j1_fu_88 == 32'd15) ? 1'b1 : 1'b0);

assign j1_12_fu_433_p2 = (j1_fu_88 + 32'd1);

assign j1_13_fu_451_p3 = ((icmp_ln54_fu_439_p2[0:0] == 1'b1) ? 32'd0 : j1_fu_88);

assign j1_14_fu_467_p3 = ((icmp_ln50_fu_427_p2[0:0] == 1'b1) ? j1_12_fu_433_p2 : j1_13_fu_451_p3);

assign j2_4_fu_627_p2 = (select_ln1027_7_fu_569_p3 + 32'd1);

assign j2_5_fu_645_p3 = ((icmp_ln44_fu_633_p2[0:0] == 1'b1) ? 32'd0 : select_ln1027_7_fu_569_p3);

assign j2_6_fu_661_p3 = ((icmp_ln40_fu_621_p2[0:0] == 1'b1) ? j2_4_fu_627_p2 : j2_5_fu_645_p3);

assign k2_4_fu_528_p3 = ((icmp_ln1027_7_fu_483_p2[0:0] == 1'b1) ? 7'd1 : add_ln22_fu_522_p2);

assign m1_8_fu_459_p3 = ((icmp_ln54_fu_439_p2[0:0] == 1'b1) ? add_ln57_fu_445_p2 : m1_fu_92);

assign m1_9_fu_475_p3 = ((icmp_ln50_fu_427_p2[0:0] == 1'b1) ? m1_fu_92 : m1_8_fu_459_p3);

assign m2_3_fu_653_p3 = ((icmp_ln44_fu_633_p2[0:0] == 1'b1) ? add_ln47_fu_639_p2 : select_ln1027_fu_562_p3);

assign m2_4_fu_669_p3 = ((icmp_ln40_fu_621_p2[0:0] == 1'b1) ? select_ln1027_fu_562_p3 : m2_3_fu_653_p3);

assign p_r_M_imag_44_fu_765_p1 = grp_fu_350_p4;

assign p_r_M_imag_46_fu_777_p1 = grp_fu_340_p4;

assign p_r_M_imag_48_fu_793_p1 = grp_fu_350_p4;

assign p_r_M_imag_fu_749_p1 = grp_fu_340_p4;

assign p_r_M_real_40_fu_761_p1 = trunc_ln388_9_fu_757_p1;

assign p_r_M_real_42_fu_773_p1 = trunc_ln388_10_fu_769_p1;

assign p_r_M_real_44_fu_789_p1 = trunc_ln328_fu_785_p1;

assign p_r_M_real_fu_745_p1 = trunc_ln388_fu_741_p1;

assign select_ln1027_10_fu_514_p3 = ((icmp_ln1027_7_fu_483_p2[0:0] == 1'b1) ? m1_9_fu_475_p3 : m1_fu_92);

assign select_ln1027_7_fu_569_p3 = ((icmp_ln1027_7_reg_922[0:0] == 1'b1) ? 32'd0 : j2_fu_80);

assign select_ln1027_8_fu_488_p3 = ((icmp_ln1027_7_fu_483_p2[0:0] == 1'b1) ? j1_14_fu_467_p3 : j1_fu_88);

assign select_ln1027_9_fu_576_p3 = ((icmp_ln1027_7_reg_922[0:0] == 1'b1) ? add40_mid1_reg_939 : add40_reg_913);

assign select_ln1027_fu_562_p3 = ((icmp_ln1027_7_reg_922[0:0] == 1'b1) ? 32'd0 : m2_fu_84);

assign sub3_i_i298_partset_fu_837_p3 = {{bitcast_ln38_2_fu_833_p1}, {bitcast_ln38_fu_829_p1}};

assign sub3_i_i302_partset_fu_853_p3 = {{bitcast_ln39_2_fu_849_p1}, {bitcast_ln39_fu_845_p1}};

assign tmp_fu_687_p3 = {{add_ln1027_1_reg_954}, {6'd0}};

assign tmp_s_fu_694_p3 = {{select_ln1027_9_reg_949}, {6'd0}};

assign trunc_ln1027_10_fu_403_p1 = j1_fu_88[5:0];

assign trunc_ln1027_11_fu_496_p1 = select_ln1027_8_fu_488_p3[3:0];

assign trunc_ln1027_12_fu_500_p1 = m1_9_fu_475_p3[5:0];

assign trunc_ln1027_13_fu_504_p1 = j1_14_fu_467_p3[5:0];

assign trunc_ln1027_14_fu_592_p1 = select_ln1027_fu_562_p3[11:0];

assign trunc_ln1027_15_fu_596_p1 = select_ln1027_7_fu_569_p3[11:0];

assign trunc_ln1027_16_fu_600_p1 = select_ln1027_7_fu_569_p3[3:0];

assign trunc_ln1027_fu_399_p1 = m1_fu_92[5:0];

assign trunc_ln328_fu_785_p1 = I_q0[15:0];

assign trunc_ln388_10_fu_769_p1 = I_q1[15:0];

assign trunc_ln388_9_fu_757_p1 = I_q0[15:0];

assign trunc_ln388_fu_741_p1 = I_q1[15:0];

assign w_13_address1 = zext_ln1027_fu_587_p1;

assign w_8_address1 = zext_ln1027_fu_587_p1;

assign zext_ln1027_fu_587_p1 = select_ln1027_8_reg_929;

assign zext_ln27_fu_701_p1 = select_ln1027_7_reg_944;

assign zext_ln28_fu_736_p1 = add_ln28_reg_969;

assign zext_ln328_fu_781_p1 = add_ln328_reg_1018_pp0_iter5_reg;

assign zext_ln388_7_fu_726_p1 = add_ln388_3_fu_721_p2;

assign zext_ln388_8_fu_753_p1 = add_ln388_4_reg_1033;

assign zext_ln388_fu_711_p1 = add_ln388_fu_706_p2;

always @ (posedge ap_clk) begin
    zext_ln388_reg_1008[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_reg_1008_pp0_iter2_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_reg_1008_pp0_iter3_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_reg_1008_pp0_iter4_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_reg_1008_pp0_iter5_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_reg_1008_pp0_iter6_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_reg_1008_pp0_iter7_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_reg_1008_pp0_iter8_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_reg_1008_pp0_iter9_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_reg_1008_pp0_iter10_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_reg_1008_pp0_iter11_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_reg_1008_pp0_iter12_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_7_reg_1023[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_7_reg_1023_pp0_iter2_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_7_reg_1023_pp0_iter3_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_7_reg_1023_pp0_iter4_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_7_reg_1023_pp0_iter5_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_7_reg_1023_pp0_iter6_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_7_reg_1023_pp0_iter7_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_7_reg_1023_pp0_iter8_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_7_reg_1023_pp0_iter9_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_7_reg_1023_pp0_iter10_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_7_reg_1023_pp0_iter11_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_8_reg_1072[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_8_reg_1072_pp0_iter3_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_8_reg_1072_pp0_iter4_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_8_reg_1072_pp0_iter5_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_8_reg_1072_pp0_iter6_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_8_reg_1072_pp0_iter7_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_8_reg_1072_pp0_iter8_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_8_reg_1072_pp0_iter9_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_8_reg_1072_pp0_iter10_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_8_reg_1072_pp0_iter11_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln388_8_reg_1072_pp0_iter12_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln328_reg_1178[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln328_reg_1178_pp0_iter7_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln328_reg_1178_pp0_iter8_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln328_reg_1178_pp0_iter9_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln328_reg_1178_pp0_iter10_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln328_reg_1178_pp0_iter11_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln328_reg_1178_pp0_iter12_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
end

endmodule //IFFT_AP_fft_stage_4_Pipeline_SKIP_X_SKIP_Y
